// AUTO-GENERATED by scripts/generate-ai-atlas.mjs — do not edit by hand.
// Source: content-src/ai-engineering-atlas/

import type { AtlasMeta } from '../llm-atlas/types'

/** Section meta plus the routing fields the registry needs. */
export interface AiAtlasMeta extends AtlasMeta {
  slug: string
  dek: string
}

export const AI_ATLAS_META: AiAtlasMeta[] = [
  {
    "id": "rag",
    "label": "RAG",
    "title": "Retrieval-Augmented Generation",
    "color": "#F0B84C",
    "icon": "layers",
    "slug": "rag",
    "dek": "The most-built system in applied AI, and the one most often described too shallowly. Chunking, retrieval, generation, and the evaluation that tells you which half is broken.",
    "subCount": 4,
    "wordCount": 912,
    "figureCount": 2,
    "equationCount": 1
  }
]
