// AUTO-GENERATED by scripts/generate-atlas-content.mjs — do not edit by hand.
// Source: scripts/vendor/atlas-logic.js

import type { AtlasPaperCategory, GlossaryEntry } from './types'

export const ATLAS_PAPERS: AtlasPaperCategory[] = [
  {
    "label": "Foundational Architecture",
    "papers": [
      {
        "a": "Vaswani et al.",
        "t": "Attention Is All You Need",
        "v": "NeurIPS 2017",
        "d": "Introduced the Transformer: self-attention, multi-head attention, sinusoidal PE, encoder-decoder. The mathematical baseline for everything that follows.",
        "url": "https://arxiv.org/abs/1706.03762"
      },
      {
        "a": "Dai et al.",
        "t": "Transformer-XL: Attentive LMs Beyond a Fixed-Length Context",
        "v": "ACL 2019 | arXiv:1901.02860",
        "d": "Segment-level recurrence and relative PE for longer effective context.",
        "url": "https://arxiv.org/abs/1901.02860"
      }
    ]
  },
  {
    "label": "Encoder-Only Models",
    "papers": [
      {
        "a": "Devlin et al.",
        "t": "BERT: Pre-training of Deep Bidirectional Transformers",
        "v": "NAACL 2019 | arXiv:1810.04805",
        "d": "MLM + NSP, bidirectional understanding, [CLS] token. Defined encoder-only pre-training.",
        "url": "https://arxiv.org/abs/1810.04805"
      },
      {
        "a": "Liu et al.",
        "t": "RoBERTa: A Robustly Optimized BERT Pretraining Approach",
        "v": "arXiv:1907.11692, 2019",
        "d": "Dynamic masking, no NSP, larger batches. Rigorous ablation showing what actually matters in BERT.",
        "url": "https://arxiv.org/abs/1907.11692"
      },
      {
        "a": "Yang et al.",
        "t": "XLNet: Generalized Autoregressive Pretraining",
        "v": "NeurIPS 2019 | arXiv:1906.08237",
        "d": "Permutation language modeling — combines autoregressive and autoencoding strengths.",
        "url": "https://arxiv.org/abs/1906.08237"
      }
    ]
  },
  {
    "label": "Decoder-Only Models",
    "papers": [
      {
        "a": "Radford et al.",
        "t": "Language Models are Unsupervised Multitask Learners (GPT-2)",
        "v": "OpenAI, 2019",
        "d": "Scale alone yields zero-shot task transfer; sparked debate about emergent abilities."
      },
      {
        "a": "Brown et al.",
        "t": "Language Models are Few-Shot Learners (GPT-3)",
        "v": "NeurIPS 2020 | arXiv:2005.14165",
        "d": "175B in-context learning at scale. Defining paper of the modern LLM era.",
        "url": "https://arxiv.org/abs/2005.14165"
      },
      {
        "a": "Touvron et al.",
        "t": "LLaMA: Open and Efficient Foundation Language Models",
        "v": "arXiv:2302.13971, 2023",
        "d": "Catalyzed open-weights ecosystem; canonical modern decoder stack (RMSNorm, SwiGLU, RoPE, Pre-Norm).",
        "url": "https://arxiv.org/abs/2302.13971"
      }
    ]
  },
  {
    "label": "Encoder-Decoder Models",
    "papers": [
      {
        "a": "Raffel et al.",
        "t": "Exploring the Limits of Transfer Learning with T5",
        "v": "JMLR 2020 | arXiv:1910.10683",
        "d": "Unified all NLP as text-to-text; span corruption pre-training; still strong baseline for seq2seq.",
        "url": "https://arxiv.org/abs/1910.10683"
      },
      {
        "a": "Lewis et al.",
        "t": "BART: Denoising Sequence-to-Sequence Pre-training",
        "v": "ACL 2020 | arXiv:1910.13461",
        "d": "Denoising autoencoder; strong for abstractive summarization.",
        "url": "https://arxiv.org/abs/1910.13461"
      }
    ]
  },
  {
    "label": "Mixture of Experts",
    "papers": [
      {
        "a": "Fedus et al.",
        "t": "Switch Transformers: Scaling to Trillion Parameter Models",
        "v": "JMLR 2022 | arXiv:2101.03961",
        "d": "Simplified top-1 routing; trillion-parameter scale; established MoE as production-viable.",
        "url": "https://arxiv.org/abs/2101.03961"
      },
      {
        "a": "DeepSeek-AI",
        "t": "DeepSeek-V3 Technical Report",
        "v": "arXiv:2412.19437, 2024",
        "d": "MLA + fine-grained MoE (256+1 experts, 8 active); auxiliary-loss-free load balancer; 14.8T tokens in 2.788M H800 GPU-hours.",
        "url": "https://arxiv.org/abs/2412.19437"
      }
    ]
  },
  {
    "label": "State Space Models & Linear Architectures",
    "papers": [
      {
        "a": "Gu et al.",
        "t": "Efficiently Modeling Long Sequences with Structured State Spaces (S4)",
        "v": "ICLR 2022 | arXiv:2111.00396",
        "d": "HiPPO matrix initialization; convolution/recurrence duality; established SSM framework.",
        "url": "https://arxiv.org/abs/2111.00396"
      },
      {
        "a": "Gu & Dao",
        "t": "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
        "v": "arXiv:2312.00752, 2023",
        "d": "Input-dependent SSM; hardware-aware parallel scan; O(n) inference; 5× throughput vs Transformers.",
        "url": "https://arxiv.org/abs/2312.00752"
      },
      {
        "a": "Peng et al.",
        "t": "RWKV: Reinventing RNNs for the Transformer Era",
        "v": "EMNLP 2023 | arXiv:2305.13048",
        "d": "Trainable in parallel; runs as RNN at inference; WKV time-mixing with learned per-channel decay.",
        "url": "https://arxiv.org/abs/2305.13048"
      },
      {
        "a": "Sun et al.",
        "t": "Retentive Network: A Successor to Transformer for LLMs",
        "v": "arXiv:2307.08621, 2023",
        "d": "Three equivalent forms (parallel/recurrent/chunk-wise); exponential decay retention mechanism.",
        "url": "https://arxiv.org/abs/2307.08621"
      },
      {
        "a": "Katharopoulos et al.",
        "t": "Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention",
        "v": "ICML 2020 | arXiv:2006.16236",
        "d": "Kernel-based linear attention achieving O(n); established linear attention literature.",
        "url": "https://arxiv.org/abs/2006.16236"
      }
    ]
  },
  {
    "label": "Tokenization",
    "papers": [
      {
        "a": "Sennrich et al.",
        "t": "Neural Machine Translation of Rare Words with Subword Units (BPE)",
        "v": "ACL 2016 | arXiv:1508.07909",
        "d": "Adapted BPE compression algorithm to NLP; defined subword tokenization paradigm.",
        "url": "https://arxiv.org/abs/1508.07909"
      },
      {
        "a": "Kudo",
        "t": "Subword Regularization: Improving NMT with Multiple Subword Candidates",
        "v": "ACL 2018 | arXiv:1804.10959",
        "d": "Probabilistic unigram tokenization via EM pruning; enables sampling for regularization.",
        "url": "https://arxiv.org/abs/1804.10959"
      },
      {
        "a": "Kudo & Richardson",
        "t": "SentencePiece: A simple and language independent subword tokenizer",
        "v": "EMNLP 2018 | arXiv:1808.06226",
        "d": "Language-independent framework; spaces marked as ▁; universally used for multilingual models.",
        "url": "https://arxiv.org/abs/1808.06226"
      },
      {
        "a": "Xue et al.",
        "t": "ByT5: Towards a Token-Free Future with Pre-trained Byte-to-Byte Models",
        "v": "TACL 2022 | arXiv:2105.13626",
        "d": "UTF-8 byte processing; vocabulary=256; zero unknown tokens.",
        "url": "https://arxiv.org/abs/2105.13626"
      }
    ]
  },
  {
    "label": "Positional Encoding",
    "papers": [
      {
        "a": "Su et al.",
        "t": "RoFormer: Enhanced Transformer with Rotary Position Embedding (RoPE)",
        "v": "Neurocomputing 2024 | arXiv:2104.09864",
        "d": "Rotation-based PE; dot products encode relative position naturally; now the dominant standard.",
        "url": "https://arxiv.org/abs/2104.09864"
      },
      {
        "a": "Press et al.",
        "t": "Train Short, Test Long: Attention with Linear Biases (ALiBi)",
        "v": "ICLR 2022 | arXiv:2108.12409",
        "d": "Adds linear distance penalty to attention scores; strong length extrapolation without PE.",
        "url": "https://arxiv.org/abs/2108.12409"
      },
      {
        "a": "Peng et al.",
        "t": "YaRN: Efficient Context Window Extension of Large Language Models",
        "v": "ICLR 2024 | arXiv:2309.00071",
        "d": "Extends RoPE beyond training length; ~2.5× fewer fine-tuning steps than position interpolation.",
        "url": "https://arxiv.org/abs/2309.00071"
      }
    ]
  },
  {
    "label": "Normalization & Activation Functions",
    "papers": [
      {
        "a": "Ba et al.",
        "t": "Layer Normalization",
        "v": "arXiv:1607.06450, 2016",
        "d": "Introduced LayerNorm; normalized across feature dimension; essential for Transformer training.",
        "url": "https://arxiv.org/abs/1607.06450"
      },
      {
        "a": "Hendrycks & Gimpel",
        "t": "Gaussian Error Linear Units (GELUs)",
        "v": "arXiv:1606.08415, 2016",
        "d": "Smooth stochastic gating; empirically outperforms ReLU in Transformers.",
        "url": "https://arxiv.org/abs/1606.08415"
      },
      {
        "a": "Zhang & Sennrich",
        "t": "Root Mean Square Layer Normalization",
        "v": "NeurIPS 2019 | arXiv:1910.07467",
        "d": "Drops mean-centering; computationally cheaper; quality matches LayerNorm. Now standard.",
        "url": "https://arxiv.org/abs/1910.07467"
      },
      {
        "a": "Shazeer",
        "t": "GLU Variants Improve Transformer",
        "v": "arXiv:2002.05202, 2020",
        "d": "Introduced SwiGLU, GeGLU; SwiGLU is now the de-facto activation standard.",
        "url": "https://arxiv.org/abs/2002.05202"
      }
    ]
  },
  {
    "label": "Scaling Laws",
    "papers": [
      {
        "a": "Kaplan et al.",
        "t": "Scaling Laws for Neural Language Models",
        "v": "arXiv:2001.08361, 2020",
        "d": "Power-law relationships between N, D, C, and loss; justified massive scaling investment.",
        "url": "https://arxiv.org/abs/2001.08361"
      },
      {
        "a": "Hoffmann et al.",
        "t": "Training Compute-Optimal Large Language Models (Chinchilla)",
        "v": "NeurIPS 2022 | arXiv:2203.15556",
        "d": "Revised scaling: model and data should scale equally at ~20 tokens/param.",
        "url": "https://arxiv.org/abs/2203.15556"
      }
    ]
  },
  {
    "label": "Post-Training & Alignment",
    "papers": [
      {
        "a": "Ouyang et al.",
        "t": "Training LMs to Follow Instructions with Human Feedback (InstructGPT)",
        "v": "NeurIPS 2022 | arXiv:2203.02155",
        "d": "Foundational RLHF: SFT → reward model → PPO; the template for instruction tuning.",
        "url": "https://arxiv.org/abs/2203.02155"
      },
      {
        "a": "Rafailov et al.",
        "t": "Direct Preference Optimization (DPO)",
        "v": "NeurIPS 2023 | arXiv:2305.18290",
        "d": "Bypasses RL loop; directly optimizes preference loss from human preference labels.",
        "url": "https://arxiv.org/abs/2305.18290"
      },
      {
        "a": "Bai et al.",
        "t": "Constitutional AI: Harmlessness from AI Feedback",
        "v": "arXiv:2212.08073, 2022",
        "d": "Replaces human preference labels with AI critique guided by a written constitution.",
        "url": "https://arxiv.org/abs/2212.08073"
      }
    ]
  },
  {
    "label": "Efficiency Optimizations",
    "papers": [
      {
        "a": "Dao et al.",
        "t": "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
        "v": "NeurIPS 2022 | arXiv:2205.14135",
        "d": "IO-aware tiled attention; never materializes O(n²) matrix in HBM; 10-20× memory reduction.",
        "url": "https://arxiv.org/abs/2205.14135"
      },
      {
        "a": "Dao",
        "t": "FlashAttention-2: Faster Attention with Better Parallelism",
        "v": "ICLR 2024 | arXiv:2307.08691",
        "d": "~2× speedup over FA1 via improved thread scheduling on modern GPUs.",
        "url": "https://arxiv.org/abs/2307.08691"
      },
      {
        "a": "Liu et al.",
        "t": "LoRA: Low-Rank Adaptation of Large Language Models",
        "v": "ICLR 2022 | arXiv:2106.09685",
        "d": "PEFT via low-rank weight decomposition; changed fine-tuning economics.",
        "url": "https://arxiv.org/abs/2106.09685"
      }
    ]
  },
  {
    "label": "Evaluation & Benchmarks",
    "papers": [
      {
        "a": "Hsieh et al.",
        "t": "RULER: What's the Real Context Size of Your Long-Context Language Models?",
        "v": "COLM 2024 | arXiv:2404.06654",
        "d": "13-task benchmark; exposed the nominal-vs-functional context gap across 17 models.",
        "url": "https://arxiv.org/abs/2404.06654"
      },
      {
        "a": "Liu et al.",
        "t": "Lost in the Middle: How LMs Use Long Contexts",
        "v": "TACL 2024",
        "d": "Models attend well to start/end but systematically miss material in the middle."
      },
      {
        "a": "Hendrycks et al.",
        "t": "Measuring Massive Multitask Language Understanding (MMLU)",
        "v": "ICLR 2021 | arXiv:2009.03300",
        "d": "57-subject knowledge benchmark; near-saturated by 2024, motivating harder successors.",
        "url": "https://arxiv.org/abs/2009.03300"
      }
    ]
  },
  {
    "label": "Recent Surveys (2024–2026)",
    "papers": [
      {
        "a": "Sun et al.",
        "t": "Speed Always Wins: A Survey on Efficient Architectures for LLMs",
        "v": "arXiv:2508.09834, 2025",
        "d": "Seven categories of efficient architectures; comprehensive 2025 taxonomy.",
        "url": "https://arxiv.org/abs/2508.09834"
      },
      {
        "a": "Patro & Agneeswaran",
        "t": "LLMOrbit: A Circular Taxonomy of Large Language Models",
        "v": "arXiv:2601.14053, 2026",
        "d": "50+ models across 8 orbital dimensions; maps the full 2026 architectural landscape.",
        "url": "https://arxiv.org/abs/2601.14053"
      }
    ]
  }
]

export const ATLAS_GLOSSARY: GlossaryEntry[] = [
  {
    "term": "Autoregressive",
    "def": "A model that predicts future values based on past values. In LLMs, predicting the next token given previous tokens."
  },
  {
    "term": "KV-Cache",
    "def": "Storing the Keys and Values of past tokens during inference so they don't need to be recomputed for every new token."
  },
  {
    "term": "MoE (Mixture of Experts)",
    "def": "An architecture where only a subset of the network's parameters (experts) are activated for any given token, saving compute."
  },
  {
    "term": "Perplexity (PPL)",
    "def": "A measurement of how well a probability model predicts a sample. Lower is better. Mathematically, the exponentiated cross-entropy loss."
  },
  {
    "term": "RoPE (Rotary Position Embedding)",
    "def": "A method to inject positional information by rotating the queries and keys in the complex plane, allowing relative distances to emerge naturally."
  },
  {
    "term": "Speculative Decoding",
    "def": "Using a small, fast model to guess multiple future tokens, and a large, slow model to verify them all at once in parallel."
  },
  {
    "term": "RLHF",
    "def": "Reinforcement Learning from Human Feedback. Training a model to maximize a reward signal derived from human preference rankings."
  }
]
