/* eslint-disable -- vendored source, see the note in the generator */
// @ts-nocheck
// AUTO-GENERATED by scripts/generate-atlas-content.mjs — do not edit by hand.
// Source: scripts/vendor/atlas-logic.js
import type { AtlasAnim } from './types'

/** Rounded-rect path helper, lifted from the original Atlas. */
function rr(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  ctx.beginPath()
  ctx.roundRect(x, y, w, h, r)
}

export const ATLAS_ANIMS: Record<string, AtlasAnim> = {
  token_pred:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const toks=["The","quick","brown","fox","[?]"],cols=["#00D9FF","#00D9FF","#00D9FF","#00D9FF","#10B981"];
    const tw=60,th=32,g=10,sx=(w-toks.length*(tw+g))/2,y=22;
    toks.forEach((tok,i)=>{
      const pulse=i===4?Math.abs(Math.sin(t*2)):1;
      ctx.globalAlpha=pulse;
      ctx.fillStyle=i===4?"rgba(16,185,129,.18)":"rgba(0,217,255,.1)";
      ctx.strokeStyle=i===4?"#10B981":"#00D9FF44";ctx.lineWidth=i===4?2:1.5;
      rr(ctx,sx+i*(tw+g),y,tw,th,6);ctx.fill();ctx.stroke();
      ctx.fillStyle=i===4?"#10B981":"#D9D3CC";
      ctx.font=(i===4?"bold ":"")+"12px 'IBM Plex Mono'";
      ctx.textAlign="center";ctx.textBaseline="middle";
      ctx.fillText(tok,sx+i*(tw+g)+tw/2,y+th/2);
      ctx.globalAlpha=1;
    });
    ctx.textBaseline="alphabetic";
    const probs=[["over",.62],["around",.2],["off",.1],["away",.08]];
    const bx=sx+4*(tw+g),by=y+th+20;
    probs.forEach(([word,p],i)=>{
      const bw=128*p*Math.min(t*1.5,1);
      ctx.fillStyle="rgba(16,185,129,.12)";ctx.fillRect(bx,by+i*24,128,18);
      ctx.fillStyle="#10B981";ctx.fillRect(bx,by+i*24,bw,18);
      ctx.fillStyle="#E8E2D9";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";
      ctx.fillText(word,bx+4,by+i*24+9);ctx.textAlign="right";
      ctx.fillText((p*100).toFixed(0)+"%",bx+124,by+i*24+9);ctx.textBaseline="alphabetic";
    });
  },
  param_scale:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ms=[{n:"GPT-1\n117M",p:.117,c:"#6BC5DB"},{n:"BERT\n340M",p:.34,c:"#8B5CF6"},{n:"GPT-2\n1.5B",p:1.5,c:"#00D9FF"},{n:"GPT-3\n175B",p:175,c:"#C77DBB"},{n:"PaLM\n540B",p:540,c:"#E0705C"},{n:"DSV3\n37B active",p:37,c:"#10B981"}];
    const maxP=600,bw=40,gap=16,sx=(w-ms.length*(bw+gap))/2,maxH=h-72;
    ms.forEach((m,i)=>{
      const bh=(m.p/maxP)*maxH*Math.min(t*.5,1);
      const x=sx+i*(bw+gap),y=h-50-bh;
      ctx.fillStyle=m.c+"18";ctx.fillRect(x,h-50-maxH,bw,maxH);
      ctx.fillStyle=m.c+"66";ctx.fillRect(x,y,bw,bh);
      ctx.fillStyle=m.c;ctx.fillRect(x,y,bw,3);
      ctx.fillStyle="#E8E2D9";ctx.font="bold 9px 'IBM Plex Mono'";ctx.textAlign="center";
      if(bh>18)ctx.fillText(m.p+"B",x+bw/2,y-6);
      ctx.fillStyle="#9D968E";ctx.font="8.5px 'IBM Plex Mono'";
      m.n.split("\n").forEach((l,li)=>ctx.fillText(l,x+bw/2,h-30+li*12));
    });
  },
  phases:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ps=[{n:"Pre-training",s:"Trillions of tokens",c:"#00D9FF",e:"📚"},{n:"Fine-tuning",s:"RLHF / DPO / SFT",c:"#10B981",e:"🎯"},{n:"Inference",s:"Frozen weights",c:"#F0B84C",e:"⚡"}];
    const pw=(w-80)/3,ph=90,y=(h-ph)/2,g=20;
    ps.forEach((p,i)=>{
      const x=20+i*(pw+g),a=Math.min((t*1.5-i*.4),1);
      if(a<=0)return;
      ctx.globalAlpha=Math.max(0,a);
      ctx.fillStyle=p.c+"14";ctx.strokeStyle=p.c+"55";ctx.lineWidth=1.5;
      rr(ctx,x,y,pw,ph,10);ctx.fill();ctx.stroke();
      ctx.font="18px serif";ctx.textAlign="center";ctx.fillStyle="#fff";ctx.fillText(p.e,x+pw/2,y+26);
      ctx.fillStyle="#E8E2D9";ctx.font="bold 12px 'Space Grotesk'";ctx.fillText(p.n,x+pw/2,y+48);
      ctx.fillStyle="#9D968E";ctx.font="10.5px 'Space Grotesk'";ctx.fillText(p.s,x+pw/2,y+66);
      if(i<2){
        ctx.strokeStyle="#3A342E";ctx.lineWidth=1.5;ctx.setLineDash([4,4]);
        ctx.beginPath();ctx.moveTo(x+pw+2,y+ph/2);ctx.lineTo(x+pw+g-2,y+ph/2);ctx.stroke();
        ctx.setLineDash([]);
      }
      ctx.globalAlpha=1;
    });
  },
  ngram:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const s=["The","cat","sat","on","the","mat"],tw=52,th=30,g=8,sx=(w-s.length*(tw+g))/2,y=28;
    s.forEach((word,i)=>{
      ctx.fillStyle="rgba(0,217,255,.1)";ctx.strokeStyle="#00D9FF30";ctx.lineWidth=1;
      rr(ctx,sx+i*(tw+g),y,tw,th,5);ctx.fill();ctx.stroke();
      ctx.fillStyle="#D9D3CC";ctx.font="12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";
      ctx.fillText(word,sx+i*(tw+g)+tw/2,y+th/2);ctx.textBaseline="alphabetic";
    });
    const fi=Math.floor((t*.7)%5),pair=[fi,fi+1];
    pair.forEach(i=>{
      ctx.fillStyle="rgba(16,185,129,.22)";ctx.strokeStyle="#10B981";ctx.lineWidth=2;
      rr(ctx,sx+i*(tw+g),y,tw,th,5);ctx.fill();ctx.stroke();
    });
    ctx.fillStyle="#9D968E";ctx.font="11px 'Space Grotesk'";ctx.textAlign="center";
    ctx.fillText(`P("${s[pair[1]]}" | "${s[pair[0]]}") = count(pair) / count(first)`,w/2,y+th+28);
  },
  w2v:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const pts=[{w:"king",x:.2,y:.22,c:"#00D9FF"},{w:"queen",x:.2,y:.58,c:"#C77DBB"},{w:"man",x:.65,y:.22,c:"#00D9FF"},{w:"woman",x:.65,y:.58,c:"#C77DBB"},{w:"river",x:.42,y:.82,c:"#10B981"},{w:"bank",x:.14,y:.82,c:"#F0B84C"}];
    for(let i=0;i<=4;i++){ctx.strokeStyle="rgba(255,255,255,.04)";ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(i*w/4,0);ctx.lineTo(i*w/4,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*h/4);ctx.lineTo(w,i*h/4);ctx.stroke();}
    const r=Math.min(t*.6,1);
    if(r>.3){ctx.strokeStyle="#8B5CF655";ctx.lineWidth=1.5;ctx.setLineDash([4,4]);[[0,1],[2,3],[0,2],[1,3]].forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(pts[a].x*w,pts[a].y*h);ctx.lineTo(pts[b].x*w,pts[b].y*h);ctx.stroke();});ctx.setLineDash([]);}
    pts.forEach(p=>{
      ctx.fillStyle=p.c+"30";ctx.strokeStyle=p.c;ctx.lineWidth=2;
      ctx.beginPath();ctx.arc(p.x*w,p.y*h,5,0,Math.PI*2);ctx.fill();ctx.stroke();
      ctx.fillStyle="#E8E2D9";ctx.font="bold 12px 'Space Grotesk'";ctx.textAlign="left";
      ctx.fillText(p.w,p.x*w+9,p.y*h+4);
    });
    ctx.fillStyle="#9D968E";ctx.font="10.5px 'Space Grotesk'";ctx.textAlign="center";
    ctx.fillText("king − man + woman ≈ queen  (the famous Word2Vec analogy)",w/2,h-8);
  },
  rnn:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const n=5,r=22,g=56,sx=28,y=h*.38,prog=Math.min(t*.55,n-1);
    for(let i=0;i<n;i++){
      const x=sx+i*(r*2+g),act=i<=prog;
      rr(ctx,x-18,y+48,36,24,5);
      ctx.fillStyle=act?"rgba(0,217,255,.28)":"rgba(0,217,255,.06)";ctx.strokeStyle=act?"#00D9FF":"#3A342E";ctx.lineWidth=1.5;
      ctx.fill();ctx.stroke();
      ctx.fillStyle=act?"#D9D3CC":"#3A342E";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";
      ctx.fillText("x"+i,x,y+61);ctx.textBaseline="alphabetic";
      ctx.fillStyle=act?"rgba(16,185,129,.2)":"rgba(16,185,129,.05)";ctx.strokeStyle=act?"#10B981":"#24211D";ctx.lineWidth=2;
      ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();
      ctx.fillStyle=act?"#10B981":"#24211D";ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";
      ctx.fillText("h"+i,x,y);ctx.textBaseline="alphabetic";
      if(act){ctx.strokeStyle="#00D9FF55";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y+48);ctx.lineTo(x,y+r+2);ctx.stroke();}
      if(i<n-1&&act){const nx=sx+(i+1)*(r*2+g);ctx.strokeStyle="#10B98166";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(nx-r,y);ctx.stroke();ctx.fillStyle="#10B98166";ctx.beginPath();ctx.moveTo(nx-r,y-4);ctx.lineTo(nx-r,y+4);ctx.lineTo(nx-r+8,y);ctx.fill();}
      if(i===0&&prog>2){const fade=Math.min((prog-2)*.6,1);ctx.globalAlpha=fade;ctx.fillStyle="#E0705C";ctx.font="9px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("grad→0",x,y-r-8);ctx.globalAlpha=1;}
    }
  },
  lstm:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const cx=w/2,cy=h*.42,rw=90,rh=52;
    ctx.fillStyle="rgba(0,217,255,.1)";ctx.strokeStyle="#00D9FF";ctx.lineWidth=2;rr(ctx,cx-rw,cy-rh,rw*2,rh*2,10);ctx.fill();ctx.stroke();
    ctx.fillStyle="#D9D3CC";ctx.font="bold 13px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("LSTM Cell",cx,cy-rh+20);
    const gates=[{n:"Forget",x:cx-65,c:"#E0705C",v:Math.abs(Math.sin(t))},{n:"Input",x:cx,c:"#10B981",v:Math.abs(Math.cos(t))},{n:"Output",x:cx+65,c:"#F0B84C",v:Math.abs(Math.sin(t+1))}];
    gates.forEach(g=>{
      ctx.fillStyle=g.c+"25";ctx.strokeStyle=g.c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,cy,16,0,Math.PI*2);ctx.fill();ctx.stroke();
      ctx.fillStyle=g.c+"88";ctx.beginPath();ctx.arc(g.x,cy,16*g.v,0,Math.PI*2);ctx.fill();
      ctx.fillStyle="#fff";ctx.font="bold 9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(g.v.toFixed(1),g.x,cy);ctx.textBaseline="alphabetic";
      ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.fillText(g.n,g.x,cy+26);
    });
    ctx.strokeStyle="#8B5CF6";ctx.lineWidth=3;ctx.setLineDash([6,3]);ctx.beginPath();ctx.moveTo(cx-rw-18,cy-18);ctx.lineTo(cx+rw+18,cy-18);ctx.stroke();ctx.setLineDash([]);
    ctx.fillStyle="#8B5CF6";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Cell State C_t — additive update path (gradients flow freely)",cx,cy-rh-8);
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("σ gates ∈ [0,1]: 0 = forget everything, 1 = keep everything",cx,h-12);
  },
  bahdanau:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const enc=["I","love","this","model"],tw=44,th=28,ey=24,g=10,sx=(w-enc.length*(tw+g))/2;
    const fi=Math.floor((t*.6)%enc.length);
    enc.forEach((word,i)=>{
      const isF=i===fi;ctx.globalAlpha=isF?1:0.3;
      ctx.fillStyle=isF?"rgba(16,185,129,.25)":"rgba(0,217,255,.08)";ctx.strokeStyle=isF?"#10B981":"#00D9FF30";ctx.lineWidth=isF?2:1;
      rr(ctx,sx+i*(tw+g),ey,tw,th,5);ctx.fill();ctx.stroke();
      ctx.fillStyle=isF?"#10B981":"#9D968E";ctx.font="12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(word,sx+i*(tw+g)+tw/2,ey+th/2);ctx.textBaseline="alphabetic";ctx.globalAlpha=1;
      if(isF){
        ctx.strokeStyle="#10B981";ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(sx+i*(tw+g)+tw/2,ey+th);ctx.lineTo(w/2,h-48);ctx.stroke();
        ctx.fillStyle="#F0B84C";ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";
        ctx.fillText("α="+(.4+i*.12).toFixed(2),sx+i*(tw+g)+tw/2+(w/2-sx-i*(tw+g)-tw/2)/2,ey+th+(h-48-ey-th)/2);
      }
    });
    ctx.fillStyle="rgba(240,184,76,.12)";ctx.strokeStyle="#F0B84C70";ctx.lineWidth=2;rr(ctx,w/2-42,h-46,84,28,6);ctx.fill();ctx.stroke();
    ctx.fillStyle="#F0B84C";ctx.font="bold 12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Decoder",w/2,h-32);ctx.textBaseline="alphabetic";
    ctx.fillStyle="#9D968E";ctx.font="10.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("c_t = Σ α_i·h_i — weighted blend of encoder states",w/2,(ey+th+h-46)/2+14);
  },
  seq2seq_bottle:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ew=w*.36,eh=40,ex=w*.05,ey=h/2-eh/2,dw=w*.36,dx=w*.59;
    ctx.fillStyle="rgba(0,217,255,.1)";ctx.strokeStyle="#00D9FF";ctx.lineWidth=2;rr(ctx,ex,ey,ew,eh,8);ctx.fill();ctx.stroke();
    ctx.fillStyle="#00D9FF";ctx.font="bold 12px 'Space Grotesk'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Encoder RNN",ex+ew/2,ey+eh/2);ctx.textBaseline="alphabetic";
    ctx.fillStyle="rgba(16,185,129,.1)";ctx.strokeStyle="#10B981";ctx.lineWidth=2;rr(ctx,dx,ey,dw,eh,8);ctx.fill();ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="bold 12px 'Space Grotesk'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Decoder RNN",dx+dw/2,ey+eh/2);ctx.textBaseline="alphabetic";
    const mx=ex+ew+(dx-ex-ew)/2,my=h/2;
    ctx.fillStyle="rgba(240,184,76,.2)";ctx.strokeStyle="#F0B84C";ctx.lineWidth=2;ctx.beginPath();ctx.arc(mx,my,14,0,Math.PI*2);ctx.fill();ctx.stroke();
    ctx.fillStyle="#F0B84C";ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("c",mx,my);ctx.textBaseline="alphabetic";
    ctx.strokeStyle="#F0B84C";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ex+ew,my);ctx.lineTo(mx-14,my);ctx.stroke();ctx.beginPath();ctx.moveTo(mx+14,my);ctx.lineTo(dx,my);ctx.stroke();
    const ts=(t*.5)%1;
    ctx.fillStyle=`rgba(240,184,76,${.8-ts*.5})`;ctx.beginPath();ctx.arc(ex+ew+ts*(dx-ex-ew),my,4,0,Math.PI*2);ctx.fill();
    ctx.fillStyle="#E0705C";ctx.font="bold 14px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("BOTTLENECK",mx,my-24);
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("All context compressed into 1 vector",mx,my+32);
  },
  enc_dec:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ew=w*.36,eh=h*.56,ex=w*.02,ey=(h-eh)/2,dw=w*.36,dy=(h-eh)/2,dx=w*.58;
    ctx.fillStyle="rgba(0,217,255,.1)";ctx.strokeStyle="#00D9FF";ctx.lineWidth=2;rr(ctx,ex,ey,ew,eh,12);ctx.fill();ctx.stroke();
    ctx.fillStyle="#00D9FF";ctx.font="bold 13px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("ENCODER",ex+ew/2,ey+24);
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.fillText("Bidirectional Self-Attn",ex+ew/2,ey+44);
    ["h₁","h₂","h₃","h₄"].forEach((hl,i)=>{const hx=ex+18+i*38,hy=ey+eh-46;ctx.fillStyle="rgba(0,217,255,.28)";ctx.strokeStyle="#00D9FF66";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(hx,hy,14,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#D9D3CC";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(hl,hx,hy);ctx.textBaseline="alphabetic";});
    const anim=Math.sin(t*1.5)*.5+.5;
    ctx.strokeStyle=`rgba(16,185,129,${.4+anim*.6})`;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(ex+ew,h/2);ctx.lineTo(dx,h/2);ctx.stroke();
    ctx.fillStyle=`rgba(16,185,129,${.4+anim*.6})`;ctx.beginPath();ctx.moveTo(dx,h/2-5);ctx.lineTo(dx,h/2+5);ctx.lineTo(dx+8,h/2);ctx.fill();
    ctx.fillStyle="#10B981";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("cross-attn",ex+ew+(dx-ex-ew)/2,h/2-10);
    ctx.fillStyle="rgba(16,185,129,.1)";ctx.strokeStyle="#10B981";ctx.lineWidth=2;rr(ctx,dx,dy,dw,eh,12);ctx.fill();ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="bold 13px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("DECODER",dx+dw/2,dy+24);
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.fillText("Masked Self-Attn + Cross-Attn",dx+dw/2,dy+44);
    ["Je","suis","ici"].forEach((tk,i)=>{const a=Math.min((t*.8-i*.4),1);if(a<=0)return;ctx.globalAlpha=a;ctx.fillStyle="rgba(16,185,129,.2)";ctx.strokeStyle="#10B98160";ctx.lineWidth=1;rr(ctx,dx+18+i*54,dy+eh-50,46,26,5);ctx.fill();ctx.stroke();ctx.fillStyle="#10B981";ctx.font="11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tk,dx+18+i*54+23,dy+eh-37);ctx.textBaseline="alphabetic";ctx.globalAlpha=1;});
  },
  posenc:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const pos=20,dims=8,cw=(w-40)/pos,ch=(h-54)/dims;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Sinusoidal PE Matrix — each column = one token's positional fingerprint",w/2,14);
    for(let p=0;p<pos;p++)for(let d=0;d<dims;d++){
      const i=Math.floor(d/2),val=d%2===0?Math.sin(p/Math.pow(10000,2*i/8)):Math.cos(p/Math.pow(10000,2*i/8));
      const a=Math.min((t*.4-p*.02),1);if(a<=0)continue;
      ctx.globalAlpha=Math.max(0,a);
      const rv=val>0?Math.floor(val*100+20):20,bv=val<0?Math.floor(-val*100+20):20;
      ctx.fillStyle=`rgb(${rv},36,${bv})`;ctx.fillRect(40+p*cw,20+d*ch,cw-1,ch-1);
    }
    ctx.globalAlpha=1;
    ctx.fillStyle="#9D968E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("Position →",w/2,h-8);
  },
  attn:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const toks=["The","cat","sat"],n=3,tw=54,th=28,g=10,sx=(w-n*(tw+g))/2,ty=18;
    toks.forEach((tok,i)=>{rr(ctx,sx+i*(tw+g),ty,tw,th,5);ctx.fillStyle="rgba(0,217,255,.1)";ctx.fill();ctx.strokeStyle="#00D9FF30";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle="#D9D3CC";ctx.font="12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tok,sx+i*(tw+g)+tw/2,ty+th/2);ctx.textBaseline="alphabetic";});
    const ms=34,mx=(w-n*ms)/2,my=62;
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("softmax(QKᵀ/√d_k) — attention weight matrix",w/2,my-9);
    const W=[[.8,.1,.1],[.2,.7,.1],[.1,.3,.6]];
    for(let r=0;r<n;r++)for(let c=0;c<n;c++){
      const v=W[r][c]*Math.min(t*.8,1);
      ctx.fillStyle=`rgba(0,217,255,${v*.85})`;ctx.fillRect(mx+c*ms,my+r*ms,ms-1,ms-1);
      ctx.strokeStyle="rgba(0,217,255,.18)";ctx.lineWidth=1;ctx.strokeRect(mx+c*ms,my+r*ms,ms-1,ms-1);
      ctx.fillStyle="#E8E2D9";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(W[r][c].toFixed(1),mx+c*ms+ms/2,my+r*ms+ms/2);ctx.textBaseline="alphabetic";
    }
    toks.forEach((tok,i)=>{ctx.fillStyle="#9D968E";ctx.font="9.5px 'IBM Plex Mono'";ctx.textAlign="right";ctx.fillText(tok,mx-5,my+i*ms+ms/2+3);ctx.textAlign="center";ctx.fillText(tok,mx+i*ms+ms/2,my+n*ms+13);});
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("→  multiply by V to get contextual representations",w/2,my+n*ms+30);
  },
  mha:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const nh=4,hw=58,hh=78,g=14,sx=(w-nh*hw-(nh-1)*g)/2;
    const cs=["#00D9FF","#10B981","#F0B84C","#C77DBB"],labs=["Syntax","Coref","Local","Semant"];
    for(let i=0;i<nh;i++){
      const x=sx+i*(hw+g),y=h*.14,a=Math.min((t*.5-i*.22),1);if(a<=0)continue;
      ctx.globalAlpha=a;ctx.fillStyle=cs[i]+"18";ctx.strokeStyle=cs[i]+"70";ctx.lineWidth=1.5;rr(ctx,x,y,hw,hh,8);ctx.fill();ctx.stroke();
      ctx.fillStyle=cs[i];ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("H"+(i+1),x+hw/2,y+16);
      ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.fillText(labs[i],x+hw/2,y+30);
      for(let r=0;r<3;r++)for(let c=0;c<3;c++){ctx.fillStyle=cs[i]+Math.floor((.15+Math.sin(i+r+c)*.1+.25)*255).toString(16).padStart(2,"0");ctx.fillRect(x+5+c*14,y+38+r*12,12,10);}
      ctx.globalAlpha=1;
    }
    const ay=h*.14+hh+14;
    for(let i=0;i<nh;i++){const x=sx+i*(hw+g)+hw/2;ctx.strokeStyle="#8B5CF630";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,ay);ctx.lineTo(w/2,ay+24);ctx.stroke();}
    ctx.fillStyle="rgba(139,92,246,.12)";ctx.strokeStyle="#8B5CF6";ctx.lineWidth=1.8;rr(ctx,sx,ay+28,nh*hw+(nh-1)*g,28,6);ctx.fill();ctx.stroke();
    ctx.fillStyle="#8B5CF6";ctx.font="bold 11px 'Space Grotesk'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Concat(h1…h4) · W_O  →  d_model output",w/2,ay+42);ctx.textBaseline="alphabetic";
  },
  ffn:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const layers=[4,10,4],cs=["#00D9FF","#10B981","#8B5CF6"],lw=55,lh=h-56,lg=(w-layers.length*lw-40)/(layers.length-1),sx=20,labs=["d_model","4·d_model","d_model"];
    layers.forEach((n,li)=>{
      const x=sx+li*(lw+lg),ng=lh/n;
      for(let ni=0;ni<n;ni++){
        const ny=28+ni*ng+ng/2,a=Math.min((t*.5-li*.3),1);if(a<=0)continue;
        ctx.globalAlpha=Math.max(0,a);
        ctx.fillStyle=cs[li]+"44";ctx.strokeStyle=cs[li];ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x+lw/2,ny,7,0,Math.PI*2);ctx.fill();ctx.stroke();
        if(li<layers.length-1){const nx2=sx+(li+1)*(lw+lg),n2=layers[li+1],ng2=lh/n2;for(let nni=0;nni<Math.min(n2,4);nni++){const nny=28+nni*ng2+ng2/2;ctx.strokeStyle=cs[li]+"15";ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(x+lw/2+7,ny);ctx.lineTo(nx2+lw/2-7,nny);ctx.stroke();}}
        ctx.globalAlpha=1;
      }
      ctx.fillStyle="#9D968E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(labs[li],x+lw/2,h-10);
    });
    ctx.fillStyle="#F0B84C";ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("Activation",sx+(lw+lg)+lw/2,h-22);
  },
  bert:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const toks=["The","[MASK]","sat","on","[MASK]","mat"],tw=60,th=32,g=8,sx=(w-toks.length*(tw+g))/2,y=22;
    toks.forEach((tok,i)=>{const isM=tok==="[MASK]";rr(ctx,sx+i*(tw+g),y,tw,th,5);ctx.fillStyle=isM?"rgba(199,125,187,.2)":"rgba(0,217,255,.1)";ctx.fill();ctx.strokeStyle=isM?"#C77DBB":"#00D9FF30";ctx.lineWidth=isM?2:1;ctx.stroke();ctx.fillStyle=isM?"#C77DBB":"#D9D3CC";ctx.font=isM?"bold 9.5px 'IBM Plex Mono'":"12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tok,sx+i*(tw+g)+tw/2,y+th/2);ctx.textBaseline="alphabetic";});
    ctx.setLineDash([3,3]);ctx.strokeStyle="#00D9FF22";ctx.lineWidth=1;[1,4].forEach(mi=>{for(let i=0;i<toks.length;i++){if(i===mi)return;ctx.beginPath();ctx.moveTo(sx+i*(tw+g)+tw/2,y+th+5);ctx.lineTo(sx+mi*(tw+g)+tw/2,y+th+5);ctx.stroke();}});ctx.setLineDash([]);
    const pa=Math.min(t-.5,1);if(pa>0){ctx.globalAlpha=pa;[{idx:1,pred:"cat",p:.82},{idx:4,pred:"the",p:.91}].forEach(({idx,pred,p})=>{const bx=sx+idx*(tw+g),by=y+th+22;rr(ctx,bx,by,tw,32,5);ctx.fillStyle="rgba(16,185,129,.15)";ctx.fill();ctx.strokeStyle="#10B981";ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle="#10B981";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText('"'+pred+'"',bx+tw/2,by+11);ctx.fillStyle="#F0B84C";ctx.font="9.5px 'IBM Plex Mono'";ctx.fillText(p,bx+tw/2,by+25);ctx.textBaseline="alphabetic";});ctx.globalAlpha=1;}
    ctx.fillStyle="#9D968E";ctx.font="10.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("← Both left AND right context visible — bidirectional →",w/2,h-10);
  },
  gpt:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const gen=["Once","upon","a","time","there"],vis=Math.min(Math.floor(t*.55)+1,gen.length),tw=58,th=32,g=8,sx=(w-gen.length*(tw+g))/2,y=26;
    for(let i=0;i<gen.length;i++){const x=sx+i*(tw+g),isNew=i===vis-1,hidden=i>=vis;rr(ctx,x,y,tw,th,5);ctx.fillStyle=isNew?"rgba(16,185,129,.2)":hidden?"rgba(26,23,20,.8)":"rgba(0,217,255,.1)";ctx.fill();ctx.strokeStyle=isNew?"#10B981":hidden?"#2A2622":"#00D9FF30";ctx.lineWidth=isNew?2:1;ctx.stroke();ctx.fillStyle=isNew?"#10B981":hidden?"#3A342E":"#D9D3CC";ctx.font="12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(hidden?"?":gen[i],x+tw/2,y+th/2);ctx.textBaseline="alphabetic";}
    if(vis>1){const lx=sx+(vis-1)*(tw+g)+tw/2;for(let i=0;i<vis-1;i++){ctx.strokeStyle="rgba(0,217,255,.22)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx+i*(tw+g)+tw/2,y-2);ctx.lineTo(lx,y-10);ctx.stroke();}}
    ctx.fillStyle="#9D968E";ctx.font="10.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Causal mask: each token only attends left — no peeking right →",w/2,y+th+24);
    ctx.fillStyle="#10B981";ctx.font="bold 10.5px 'Space Grotesk'";ctx.fillText("Token generated one-at-a-time; appended as new context",w/2,y+th+42);
  },
  causal_mask:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const n=5,cs=24,sx=(w-n*cs)/2,sy=(h-n*cs)/2-10;
    ctx.fillStyle="#9D968E";ctx.font="11px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Causal Mask (Upper Triangular = -∞)",w/2,sy-16);
    for(let r=0;r<n;r++)for(let c=0;c<n;c++){
      const isMasked=c>r;
      const ts=Math.min(t*.8,1);
      ctx.globalAlpha=ts;
      ctx.fillStyle=isMasked?"rgba(224,112,92,.15)":"rgba(16,185,129,.15)";
      ctx.fillRect(sx+c*cs,sy+r*cs,cs-1,cs-1);
      ctx.strokeStyle=isMasked?"#E0705C40":"#10B98140";
      ctx.lineWidth=1;
      ctx.strokeRect(sx+c*cs,sy+r*cs,cs-1,cs-1);
      ctx.fillStyle=isMasked?"#E0705C":"#10B981";
      ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";
      ctx.fillText(isMasked?"-∞":"0",sx+c*cs+cs/2,sy+r*cs+cs/2);
      ctx.textBaseline="alphabetic";
    }
    ctx.globalAlpha=1;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Prevents attending to future tokens during training",w/2,sy+n*cs+22);
  },
  t5:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ew=w*.37,eh=h*.54,ex=w*.02,ey=(h-eh)/2,dw=w*.37,dx=w*.59,dy=(h-eh)/2;
    ctx.fillStyle="rgba(0,217,255,.1)";ctx.strokeStyle="#00D9FF";ctx.lineWidth=2;rr(ctx,ex,ey,ew,eh,12);ctx.fill();ctx.stroke();
    ctx.fillStyle="#00D9FF";ctx.font="bold 13px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("ENCODER",ex+ew/2,ey+22);
    ["translate to German:","Hello world"].forEach((s,i)=>{const by=ey+40+i*30;rr(ctx,ex+8,by,ew-16,24,4);ctx.fillStyle=i===0?"rgba(240,184,76,.15)":"rgba(0,217,255,.18)";ctx.fill();ctx.strokeStyle=i===0?"#F0B84C40":"#00D9FF40";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle="#D9D3CC";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s,ex+ew/2,by+12);ctx.textBaseline="alphabetic";});
    const anim=Math.sin(t*1.5)*.5+.5;ctx.strokeStyle=`rgba(16,185,129,${.5+anim*.5})`;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(ex+ew,h/2);ctx.lineTo(dx,h/2);ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("cross-attn",ex+ew+(dx-ex-ew)/2,h/2-9);
    ctx.fillStyle="rgba(16,185,129,.1)";ctx.strokeStyle="#10B981";ctx.lineWidth=2;rr(ctx,dx,dy,dw,eh,12);ctx.fill();ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="bold 13px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("DECODER",dx+dw/2,dy+22);
    ["Hallo","Welt"].forEach((tk,i)=>{const a=Math.min((t*.8-i*.5),1);if(a<=0)return;ctx.globalAlpha=a;rr(ctx,dx+12+i*70,dy+eh-50,62,26,5);ctx.fillStyle="rgba(16,185,129,.2)";ctx.fill();ctx.strokeStyle="#10B98160";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle="#10B981";ctx.font="11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tk,dx+12+i*70+31,dy+eh-37);ctx.textBaseline="alphabetic";ctx.globalAlpha=1;});
  },
  moe:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ne=6,ew=46,eh=56,eg=12,sx=(w-ne*(ew+eg))/2,ey=h-84,tx=w/2,ty=22;
    rr(ctx,tx-28,ty,56,26,6);ctx.fillStyle="rgba(0,217,255,.2)";ctx.fill();ctx.strokeStyle="#00D9FF";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#fff";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("token",tx,ty+13);ctx.textBaseline="alphabetic";
    const ry=68;rr(ctx,tx-44,ry,88,24,6);ctx.fillStyle="rgba(240,184,76,.14)";ctx.fill();ctx.strokeStyle="#F0B84C";ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle="#F0B84C";ctx.font="bold 10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Router (top-k)",tx,ry+12);ctx.textBaseline="alphabetic";
    ctx.strokeStyle="#00D9FF40";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(tx,ty+26);ctx.lineTo(tx,ry);ctx.stroke();
    const active=[1,4],co=Math.floor(t*.35)%2,an=[active[co%2],active[(co+1)%2]];
    for(let e=0;e<ne;e++){const ex=sx+e*(ew+eg),isA=an.includes(e);ctx.fillStyle=isA?"rgba(16,185,129,.2)":"rgba(26,23,20,.5)";ctx.strokeStyle=isA?"#10B981":"#3A342E";ctx.lineWidth=isA?2:1;rr(ctx,ex,ey,ew,eh,8);ctx.fill();ctx.stroke();ctx.fillStyle=isA?"#10B981":"#3A342E";ctx.font=(isA?"bold ":"")+"10.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("E"+(e+1),ex+ew/2,ey+eh/2);ctx.textBaseline="alphabetic";ctx.strokeStyle=isA?"rgba(16,185,129,.65)":"rgba(58,52,46,.35)";ctx.lineWidth=isA?2:1;ctx.beginPath();ctx.moveTo(tx,ry+24);ctx.lineTo(ex+ew/2,ey);ctx.stroke();}
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Only top-k experts activated per token — rest contribute zero",w/2,h-10);
  },
  ssm:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const sw=118,sh=48,sx=(w-sw)/2,sy=26;
    ctx.fillStyle="rgba(139,92,246,.14)";ctx.strokeStyle="#8B5CF6";ctx.lineWidth=2;rr(ctx,sx,sy,sw,sh,8);ctx.fill();ctx.stroke();
    ctx.fillStyle="#8B5CF6";ctx.font="bold 11.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("State x_k",sx+sw/2,sy+sh/2);ctx.textBaseline="alphabetic";
    const n=5,tw=38,th=24,iy=h-54,tg=8,isx=(w-n*(tw+tg))/2;
    for(let i=0;i<n;i++){const ix=isx+i*(tw+tg),act=i<=Math.floor(t*.55)%n;rr(ctx,ix,iy,tw,th,5);ctx.fillStyle=act?"rgba(0,217,255,.28)":"rgba(0,217,255,.06)";ctx.fill();ctx.strokeStyle=act?"#00D9FF":"#3A342E60";ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=act?"#D9D3CC":"#3A342E";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("u"+i,ix+tw/2,iy+th/2);ctx.textBaseline="alphabetic";if(act){ctx.strokeStyle="#00D9FF55";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(ix+tw/2,iy);ctx.lineTo(sx+sw/2,sy+sh);ctx.stroke();}}
    const my=sy+sh+52;rr(ctx,sx-38,my,sw+76,38,8);ctx.fillStyle="rgba(16,185,129,.1)";ctx.fill();ctx.strokeStyle="#10B98160";ctx.lineWidth=1.5;ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="bold 10.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Mamba: B, C, Δ = f(input) — selective",sx+sw/2,my+13);ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.fillText("O(1) memory/step at inference — O(n) total",sx+sw/2,my+28);ctx.textBaseline="alphabetic";
  },
  linAttn:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const n=6,d=4,half=w/2-4;
    ctx.fillStyle="#9D968E";ctx.font="bold 10.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Exact O(n²)",w*.25,18);ctx.fillText("Linear O(n)",w*.75,18);
    ctx.strokeStyle="#3A342E";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(half,14);ctx.lineTo(half,h-14);ctx.stroke();
    const cs=Math.min((half-30)/n,28);
    for(let i=0;i<n;i++)for(let j=0;j<n;j++){ctx.globalAlpha=Math.min(t*.5,1);ctx.fillStyle=`rgba(0,217,255,${.25+j/n*.45})`;ctx.fillRect(28+j*cs,26+i*cs,cs-1,cs-1);}
    ctx.globalAlpha=1;ctx.fillStyle="#E0705C";ctx.font="bold 12px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(n+"x"+n+"="+n*n+" ops",w*.25,26+n*cs+18);
    const ms=Math.min((half-30)/d,28),ox=half+28;
    for(let i=0;i<d;i++)for(let j=0;j<d;j++){const a=Math.min((t-.6)*.6,1);ctx.globalAlpha=Math.max(0,a);ctx.fillStyle=`rgba(16,185,129,${.3+j/d*.5})`;ctx.fillRect(ox+j*ms,26+i*ms,ms-1,ms-1);}
    ctx.globalAlpha=1;ctx.fillStyle="#10B981";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("φ(K)ᵀV: "+d+"x"+d+"="+d*d,w*.75,26+d*ms+18);ctx.fillText("then n×"+d*d+"="+n*d*d+" ops",w*.75,26+d*ms+34);
  },
  rwkv:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const n=6,r=18,g=52,sx=22,y=h*.35;
    for(let i=0;i<n;i++){const x=sx+i*(r*2+g),decay=Math.exp(-(n-1-i)*.6);ctx.globalAlpha=decay*.9+.1;ctx.fillStyle=`rgba(139,92,246,${decay*.4})`;ctx.strokeStyle=`rgba(139,92,246,${decay*.8})`;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#8B5CF6";ctx.font="bold 9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("v"+i,x,y);ctx.textBaseline="alphabetic";if(i===n-1){ctx.fillStyle="#9D968E";ctx.font="8.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("current",x,y+r+13);}ctx.globalAlpha=1;}
    const outX=w-52,outY=y;ctx.strokeStyle="#F0B84C";ctx.lineWidth=1.5;
    for(let i=0;i<n;i++){const x=sx+i*(r*2+g);ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(outX,outY);ctx.stroke();}
    ctx.fillStyle="rgba(240,184,76,.18)";ctx.strokeStyle="#F0B84C";ctx.lineWidth=2;ctx.beginPath();ctx.arc(outX,outY,20,0,Math.PI*2);ctx.fill();ctx.stroke();
    ctx.fillStyle="#F0B84C";ctx.font="bold 9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("wkv_t",outX,outY);ctx.textBaseline="alphabetic";
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Exponential time-decay w learned per channel; runs as RNN at inference",w/2,h-10);
  },
  retnet:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const n=5,r=18,g=54,sx=28,y=h*.35,gamma=.82;
    for(let i=0;i<n;i++){const x=sx+i*(r*2+g),act=i<=Math.floor(t*.5)%n;ctx.fillStyle=act?"rgba(16,185,129,.22)":"rgba(16,185,129,.05)";ctx.strokeStyle=act?"#10B981":"#24211D";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=act?"#10B981":"#24211D";ctx.font="bold 9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("p"+i,x,y);ctx.textBaseline="alphabetic";}
    for(let i=0;i<n-1;i++){const x1=sx+i*(r*2+g)+r,x2=sx+(i+1)*(r*2+g)-r,dec=Math.pow(gamma,n-2-i);ctx.strokeStyle=`rgba(16,185,129,${dec*.8})`;ctx.lineWidth=1+dec;ctx.beginPath();ctx.moveTo(x1,y);ctx.lineTo(x2,y);ctx.stroke();ctx.fillStyle="#9D968E";ctx.font="8px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("γ^"+(n-2-i),x1+(x2-x1)/2,y-r-4);}
    const my=y+r+36;ctx.fillStyle="rgba(139,92,246,.1)";ctx.strokeStyle="#8B5CF660";ctx.lineWidth=1.5;rr(ctx,28,my,w-56,40,8);ctx.fill();ctx.stroke();
    ctx.fillStyle="#8B5CF6";ctx.font="bold 10.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("γ="+gamma+" retention rate — 3 equivalent forms",w/2,my+13);ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.fillText("Parallel (train)  ·  Recurrent (inference)  ·  Chunk-wise",w/2,my+28);ctx.textBaseline="alphabetic";
  },
  toktradeoff:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const apps=[{n:"Characters",toks:["u","n","h","a","p","p","y"],c:"#E0705C",v:"26 vocab"},{n:"BPE",toks:["un","happy"],c:"#10B981",v:"50K vocab"},{n:"WordPiece",toks:["un","##happy"],c:"#F0B84C",v:"30K vocab"},{n:"Full Word",toks:["unhappy"],c:"#00D9FF",v:"∞ vocab"}];
    const pw=(w-40)/apps.length;
    apps.forEach((ap,i)=>{
      const px=20+i*pw,a=Math.min((t*.5-i*.18),1);if(a<=0)return;
      ctx.globalAlpha=a;ctx.fillStyle="#9D968E";ctx.font="bold 10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(ap.n,px+pw/2-10,22);
      ctx.fillStyle="#3A342E";ctx.font="9px 'IBM Plex Mono'";ctx.fillText(ap.v,px+pw/2-10,36);
      let cx_=px+4,cy=46;
      ap.toks.forEach(tok=>{const cw_=tok.length*7+10;if(cx_+cw_>px+pw-4){cx_=px+4;cy+=26;}rr(ctx,cx_,cy,cw_,20,4);ctx.fillStyle=ap.c+"22";ctx.fill();ctx.strokeStyle=ap.c+"88";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=ap.c;ctx.font="9.5px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText(tok,cx_+4,cy+10);ctx.textBaseline="alphabetic";cx_+=cw_+4;});
      ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(ap.toks.length+" token(s)",px+pw/2-10,cy+34);
      ctx.globalAlpha=1;
    });
  },
  bpe:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const steps=[{toks:["l","o","w","e","r"," ","l","o","w"," ","n","e","w","e","r"],hl:[]},{toks:["l","o","w","er"," ","l","o","w"," ","n","e","w","er"],hl:[3,12]},{toks:["l","ow","er"," ","l","ow"," ","n","e","w","er"],hl:[1,5]},{toks:["low","er"," ","low"," ","n","e","w","er"],hl:[0,3]}];
    const si=Math.min(Math.floor(t*.45),steps.length-1),s=steps[si],tw_=30,th=26,g=5,sx=(w-s.toks.length*(tw_+g))/2,y=26;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("BPE Step "+si+": "+["Initial chars","Merge 'er'","Merge 'ow'","Merge 'low'"][si],w/2,14);
    s.toks.forEach((tok,i)=>{const isH=s.hl.includes(i);rr(ctx,sx+i*(tw_+g),y,tw_,th,4);ctx.fillStyle=isH?"rgba(16,185,129,.25)":"rgba(0,217,255,.1)";ctx.fill();ctx.strokeStyle=isH?"#10B981":"#00D9FF30";ctx.lineWidth=isH?2:1;ctx.stroke();ctx.fillStyle=isH?"#10B981":"#D9D3CC";ctx.font="11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tok===" "?"_":tok,sx+i*(tw_+g)+tw_/2,y+th/2);ctx.textBaseline="alphabetic";});
    const by=y+th+22;[["er",3],["ow",2],["lo",1]].forEach(([p,f],i)=>{ctx.fillStyle="rgba(16,185,129,.15)";ctx.fillRect(20,by+i*24,f*44,16);ctx.fillStyle="#10B981";ctx.fillRect(20,by+i*24,f*44*(si>0?.95:.5),16);ctx.fillStyle="#E8E2D9";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText('"'+p+'": count='+f,24+f*44+8,by+i*24+8);ctx.textBaseline="alphabetic";});
  },
  wordpiece:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("WordPiece: merge by likelihood gain — '##' marks continuation subwords",w/2,14);
    const rows=[{w:"unbelievable",bpe:["un","believ","able"],wp:["un","##believ","##able"]},{w:"running",bpe:["run","ning"],wp:["run","##ning"]},{w:"tokenization",bpe:["token","ization"],wp:["token","##ization"]}];
    rows.forEach((row,ri)=>{
      const ry=30+ri*58;ctx.fillStyle="#E8E2D9";ctx.font="bold 11.5px 'IBM Plex Mono'";ctx.textAlign="left";ctx.fillText('"'+row.w+'"',14,ry+14);
      let bx=14;ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.fillText("BPE:",bx,ry+30);bx+=36;
      row.bpe.forEach(tok=>{const cw_=tok.length*7+10;rr(ctx,bx,ry+20,cw_,18,3);ctx.fillStyle="rgba(0,217,255,.15)";ctx.fill();ctx.strokeStyle="#00D9FF40";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle="#9D968E";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText(tok,bx+4,ry+29);ctx.textBaseline="alphabetic";bx+=cw_+4;});
      bx+=14;ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.fillText("WP:",bx,ry+30);bx+=30;
      row.wp.forEach(tok=>{const cw_=tok.length*7+10;rr(ctx,bx,ry+20,cw_,18,3);ctx.fillStyle="rgba(16,185,129,.15)";ctx.fill();ctx.strokeStyle="#10B98140";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle="#10B981";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText(tok,bx+4,ry+29);ctx.textBaseline="alphabetic";bx+=cw_+4;});
    });
  },
  sp:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const text="Hello world! 你好世界",sp=["▁Hello","▁world","!","▁你","好","世","界"];
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText('Input: "'+text+'"',14,18);
    const drawRow=(toks,lbl,y,c)=>{ctx.fillStyle="#9D968E";ctx.font="bold 9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText(lbl,14,y);let cx_=14,ry=y+8;toks.forEach(tok=>{const cw_=Math.max(tok.length*7,14)+10;if(cx_+cw_>w-14){cx_=14;ry+=24;}rr(ctx,cx_,ry,cw_,18,3);ctx.fillStyle=c+"20";ctx.fill();ctx.strokeStyle=c+"66";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=c;ctx.font="9.5px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText(tok.slice(0,10),cx_+4,ry+9);ctx.textBaseline="alphabetic";cx_+=cw_+4;});return ry+26;};
    const a=Math.min(t*.5,1);ctx.globalAlpha=a;
    let y=drawRow(sp,"SentencePiece (▁=word boundary, language-agnostic):",28,"#10B981");
    const byteArr=[...(new TextEncoder().encode(text))].map(b=>b.toString());
    drawRow(byteArr.slice(0,18),"Byte-level (UTF-8, vocab=256, zero unknowns):",y+6,"#8B5CF6");
    ctx.globalAlpha=1;ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Byte-level: 3-4x longer sequences but universal coverage",w/2,h-10);
  },
  acts:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const fns=[{n:"ReLU",fn:x=>Math.max(0,x),c:"#E0705C"},{n:"GELU",fn:x=>x*.5*(1+Math.tanh(Math.sqrt(2/Math.PI)*(x+.044715*x*x*x))),c:"#10B981"},{n:"SwiGLU",fn:x=>x*(1/(1+Math.exp(-x)))*(Math.max(0,x)*.7+.5),c:"#8B5CF6"}];
    const pw=(w-56)/3,ph=h-52,py=28,g=16;
    fns.forEach((fn,fi)=>{
      const px=16+fi*(pw+g);ctx.fillStyle="#9D968E";ctx.font="bold 10.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(fn.n,px+pw/2,py-9);
      ctx.strokeStyle="#3A342E";ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px,py+ph);ctx.stroke();ctx.beginPath();ctx.moveTo(px,py+ph/2);ctx.lineTo(px+pw,py+ph/2);ctx.stroke();
      const sy=ph/4,a=Math.min(t*.65,1);ctx.strokeStyle=fn.c;ctx.lineWidth=2.5;ctx.globalAlpha=a;ctx.beginPath();
      for(let i=0;i<=80;i++){const x=-3+6*i/80,y=fn.fn(x),cx_=px+i*pw/80,cy_=py+ph/2-y*sy;i===0?ctx.moveTo(cx_,cy_):ctx.lineTo(cx_,cy_);}
      ctx.stroke();ctx.globalAlpha=1;
      if(fi===0){ctx.fillStyle="#E0705C18";ctx.fillRect(px,py,pw/2,ph);ctx.fillStyle="#E0705C";ctx.font="8.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("dead zone",px+pw/4,py+ph-8);}
    });
  },
  norm:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const drawDist=(cx,cy,mu,sigma,c,lbl)=>{ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();const range=sigma*5;for(let i=0;i<=80;i++){const x=mu-range/2+range*i/80,y=Math.exp(-.5*((x-mu)/sigma)**2)/(sigma*Math.sqrt(2*Math.PI));const px=cx+(x-mu)*18,py_=cy-y*56;i===0?ctx.moveTo(px,py_):ctx.lineTo(px,py_);}ctx.stroke();ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(lbl,cx,cy+16);};
    const a=Math.min(t*.7,1);ctx.globalAlpha=a;
    drawDist(w*.24,h*.52,0,2.2,"#E0705C80","Unstable: σ=2.2");
    drawDist(w*.76,h*.52,0,.5,"#10B981","Stable: σ=0.5");
    ctx.globalAlpha=1;ctx.strokeStyle="#8B5CF6";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w*.36,h*.5);ctx.lineTo(w*.62,h*.5);ctx.stroke();ctx.fillStyle="#8B5CF6";ctx.beginPath();ctx.moveTo(w*.62,h*.5-5);ctx.lineTo(w*.62,h*.5+5);ctx.lineTo(w*.62+8,h*.5);ctx.fill();
    ctx.fillStyle="#8B5CF6";ctx.font="bold 10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Norm (LayerNorm / RMSNorm)",w/2,h*.5-12);
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("RMSNorm skips mean-centering — faster, same quality",w/2,h-10);
  },
  rope:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const cx=w/2,cy=h/2,r=Math.min(w,h)*.28;
    ctx.strokeStyle="#2A2622";ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();
    const pos=[0,4,8,14],cs=["#00D9FF","#10B981","#F0B84C","#C77DBB"],theta=.25;
    pos.forEach((m,i)=>{const ang=m*theta+t*.18,vx=Math.cos(ang)*r,vy=-Math.sin(ang)*r;ctx.strokeStyle=cs[i];ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+vx,cy+vy);ctx.stroke();ctx.fillStyle=cs[i];ctx.beginPath();ctx.arc(cx+vx,cy+vy,5,0,Math.PI*2);ctx.fill();ctx.font="bold 9.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText("m="+m,cx+vx*1.2,cy+vy*1.2+4);});
    ctx.fillStyle="#444";ctx.beginPath();ctx.arc(cx,cy,3,0,Math.PI*2);ctx.fill();
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Rotate Q/K by m·θ — dot product depends only on (m−n)",cx,h-28);ctx.fillText("Relative position from absolute rotations — parameter-free",cx,h-12);
  },
  o2:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const lens=[1,2,4,8,16,32],maxN=32,bw=36,g=9,sx=(w-lens.length*(bw+g))/2,maxH=h-72;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Memory vs. Sequence Length — Attention Bottleneck",w/2,16);
    lens.forEach((n,i)=>{const x=sx+i*(bw+g),lh=(n/maxN)*maxH*.42*Math.min(t,1),qh=(n*n/(maxN*maxN))*maxH*Math.min(t,1);ctx.fillStyle="rgba(16,185,129,.68)";ctx.fillRect(x,h-46-lh,bw/2-1,lh);ctx.fillStyle="rgba(224,112,92,.68)";ctx.fillRect(x+bw/2+1,h-46-qh,bw/2-1,qh);ctx.fillStyle="#9D968E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(n+"K",x+bw/2,h-28);});
    ctx.fillStyle="#10B981";ctx.fillRect(sx,h-16,14,9);ctx.fillStyle="#E8E2D9";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("KV-cache O(n)",sx+18,h-9);
    ctx.fillStyle="#E0705C";ctx.fillRect(sx+132,h-16,14,9);ctx.fillText("Attn matrix O(n²)",sx+150,h-9);
  },
  ruler:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const models=[{n:"GPT-4",s:[99,97,91,84],c:"#10B981"},{n:"Llama3-70B",s:[98,93,84,68],c:"#00D9FF"},{n:"Mistral-L",s:[97,87,74,55],c:"#F0B84C"},{n:"Model-X",s:[95,72,48,22],c:"#E0705C"}];
    const lens=["4K","32K","64K","128K"],cw=(w-80)/lens.length,ch=h-72,sx=55,sy=18;
    [0,25,50,75,100].forEach(p=>{const y=sy+ch*(1-p/100);ctx.strokeStyle="rgba(255,255,255,.04)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,y);ctx.lineTo(sx+cw*lens.length,y);ctx.stroke();ctx.fillStyle="#3A342E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="right";ctx.fillText(p+"%",sx-4,y+3);});
    models.forEach(m=>{ctx.strokeStyle=m.c;ctx.lineWidth=2;ctx.beginPath();m.s.forEach((s,i)=>{const x=sx+i*cw+cw/2,y=sy+ch*(1-s/100)*Math.min(t*.65,1);i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.stroke();m.s.forEach((s,i)=>{const x=sx+i*cw+cw/2,y=sy+ch*(1-s/100)*Math.min(t*.65,1);ctx.fillStyle=m.c;ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fill();});});
    lens.forEach((l,i)=>{ctx.fillStyle="#9D968E";ctx.font="9.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(l,sx+i*cw+cw/2,sy+ch+16);});
    models.forEach((m,i)=>{ctx.fillStyle=m.c;ctx.fillRect(sx+i*70,sy+ch+28,12,8);ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText(m.n,sx+i*70+16,sy+ch+36);});
  },
  ssa:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const lens=[4,8,32,64,128,256,512,1000],maxV=1000*1000*.022,cw=w-54,ch=h-62,sx=36,sy=16;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Prefill Time: FA-2 vs SSA — vendor-reported at scale",w/2,sy-6);
    const a=Math.min(t*.6,1);ctx.globalAlpha=a;
    ctx.strokeStyle="#E0705C";ctx.lineWidth=2.5;ctx.beginPath();lens.forEach((n,i)=>{const x=sx+i*cw/(lens.length-1),y=sy+ch*(1-Math.min(n*n*.022/maxV,1));i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.stroke();
    ctx.strokeStyle="#10B981";ctx.lineWidth=2.5;ctx.beginPath();lens.forEach((n,i)=>{const x=sx+i*cw/(lens.length-1),y=sy+ch*(1-Math.min(n*Math.log2(n+1)*.022/maxV,1));i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.stroke();ctx.globalAlpha=1;
    ctx.fillStyle="#E0705C";ctx.font="bold 9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("FA2 O(n²)",sx+cw-100,sy+24);ctx.fillStyle="#10B981";ctx.fillText("SSA ~O(n log n)",sx+cw-100,sy+40);
    lens.forEach((n,i)=>{ctx.fillStyle="#3A342E";ctx.font="8.5px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(n+"K",sx+i*cw/(lens.length-1),sy+ch+14);});
    rr(ctx,sx+cw-186,sy+ch-46,182,40,7);ctx.fillStyle="rgba(16,185,129,.1)";ctx.fill();ctx.strokeStyle="#10B98140";ctx.lineWidth=1;ctx.stroke();
    ctx.fillStyle="#10B981";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("56.2× speedup @ 1M tokens",sx+cw-95,sy+ch-28);ctx.textBaseline="alphabetic";
    ctx.fillStyle="#E0705C";ctx.font="9px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("⚠ Vendor-reported figures — pending independent reproduction",w/2,h-8);
  },
  datawall:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const yrs=[2020,2022,2024,2026,2028,2030],cw=w-56,ch=h-66,sx=36,sy=18;
    const wX=sx+((2028-2020)/10)*cw;
    ctx.strokeStyle="#E0705C";ctx.lineWidth=1.8;ctx.setLineDash([6,3]);ctx.beginPath();ctx.moveTo(wX,sy);ctx.lineTo(wX,sy+ch);ctx.stroke();ctx.setLineDash([]);
    ctx.fillStyle="#E0705C";ctx.font="bold 9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Data Wall ~2028",wX,sy-6);
    const a=Math.min(t*.5,1);ctx.globalAlpha=a;
    ctx.fillStyle="rgba(0,217,255,.18)";ctx.beginPath();ctx.moveTo(sx,sy+ch);yrs.forEach(y=>{const x=sx+((y-2020)/10)*cw,frac=Math.min((y-2020)/8,1);ctx.lineTo(x,sy+ch-frac*ch);});ctx.lineTo(sx+cw,sy+ch);ctx.closePath();ctx.fill();
    ctx.strokeStyle="#00D9FF";ctx.lineWidth=2.5;ctx.beginPath();yrs.forEach((y,i)=>{const x=sx+((y-2020)/10)*cw,frac=Math.min((y-2020)/8,1);i===0?ctx.moveTo(x,sy+ch-frac*ch):ctx.lineTo(x,sy+ch-frac*ch);});ctx.stroke();ctx.globalAlpha=1;
    ctx.strokeStyle="#E0705C40";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+cw,sy);ctx.stroke();
    ctx.fillStyle="#E0705C";ctx.font="9px 'Space Grotesk'";ctx.textAlign="right";ctx.fillText("~300T tokens (Epoch AI)",sx+cw,sy-5);
    yrs.forEach(y=>{ctx.fillStyle="#3A342E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(y,sx+((y-2020)/10)*cw,sy+ch+14);});
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("Synthetic data + multimodal + efficiency gains = path forward",w/2,sy+ch+30);
  },
  scaling:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const cw=w-60,ch=h-64,sx=40,sy=18;
    ctx.strokeStyle="#3A342E";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx,sy+ch);ctx.stroke();ctx.beginPath();ctx.moveTo(sx,sy+ch);ctx.lineTo(sx+cw,sy+ch);ctx.stroke();
    const a=Math.min(t*.55,1);ctx.strokeStyle="#00D9FF";ctx.lineWidth=3;ctx.globalAlpha=a;ctx.beginPath();
    for(let i=0;i<=100;i++){const x=sx+i*cw/100,logN=i/100*4,loss=2.9*Math.exp(-.42*logN),y=sy+ch*(1-Math.min(loss/2.9,1));i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}
    ctx.stroke();ctx.globalAlpha=1;
    [{n:"GPT-1",l:.3,loss:2.7,c:"#6BC5DB"},{n:"GPT-3",l:2.5,loss:1.42,c:"#8B5CF6"},{n:"PaLM",l:2.9,loss:1.1,c:"#C77DBB"}].forEach(p=>{const x=sx+p.l/4*cw,y=sy+ch*(1-p.loss/2.9);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(x,y,5.5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#E8E2D9";ctx.font="bold 9px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText(p.n,x+8,y+4);});
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("L(N) ∝ N^(-0.076) — smooth predictable power law",w/2,h-8);
  },
  chinchilla:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const cw=w-60,ch=h-64,sx=36,sy=18,maxN=200;
    ctx.strokeStyle="#3A342E";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx,sy+ch);ctx.stroke();ctx.beginPath();ctx.moveTo(sx,sy+ch);ctx.lineTo(sx+cw,sy+ch);ctx.stroke();
    const a=Math.min(t*.55,1);ctx.globalAlpha=a;
    ctx.strokeStyle="#00D9FF";ctx.lineWidth=2.5;ctx.beginPath();for(let n=1;n<=maxN;n++){const x=sx+n/maxN*cw,y=sy+ch*(1-n/maxN);n===1?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();
    ctx.strokeStyle="#10B981";ctx.lineWidth=2.5;ctx.setLineDash([6,4]);ctx.beginPath();for(let n=1;n<=maxN;n++){const d=20*n,x=sx+n/maxN*cw,y=sy+ch*(1-Math.min(d/(20*maxN),1));n===1?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;
    [{n:"GPT-3",nm:175,dm:300,c:"#E0705C"},{n:"Chinchilla",nm:70,dm:1400,c:"#10B981"}].forEach(m=>{const x=sx+m.nm/maxN*cw,y=sy+ch*(1-Math.min(m.dm/(20*maxN),1));ctx.fillStyle=m.c+"44";ctx.strokeStyle=m.c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#E8E2D9";ctx.font="bold 9px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(m.n,x,y-12);});
    ctx.fillStyle="#00D9FF";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("N (model size) →",sx,sy+ch+15);ctx.fillStyle="#10B981";ctx.textAlign="right";ctx.fillText("D* = 20·N →",sx+cw,sy+ch+15);
  },
  timeline:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const ms=[{n:"GPT-1",y:2018,p:.117,c:"#6BC5DB"},{n:"GPT-3",y:2020,p:175,c:"#00D9FF"},{n:"PaLM",y:2022,p:540,c:"#C77DBB"},{n:"Mixtral",y:2023.5,p:46.7,act:12.9,c:"#10B981"},{n:"DSV3",y:2025,p:671,act:37,c:"#F0B84C"}];
    const minY=2017,maxY=2026,logM=Math.log10(700),cw=w-56,ch=h-66,sx=32,sy=18;
    ctx.strokeStyle="#3A342E";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx,sy+ch);ctx.stroke();ctx.beginPath();ctx.moveTo(sx,sy+ch);ctx.lineTo(sx+cw,sy+ch);ctx.stroke();
    for(let y=2018;y<=2026;y+=2){const x=sx+((y-minY)/(maxY-minY))*cw;ctx.strokeStyle="#2A2622";ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(x,sy);ctx.lineTo(x,sy+ch);ctx.stroke();ctx.fillStyle="#3A342E";ctx.font="9px 'IBM Plex Mono'";ctx.textAlign="center";ctx.fillText(y,x,sy+ch+14);}
    const a=Math.min(t*.42,1);
    ms.forEach((m,i)=>{const mx=sx+((m.y-minY)/(maxY-minY))*cw,logP=Math.log10(Math.max(m.p,.1)),my=sy+ch*(1-logP/logM),ia=Math.min((a*ms.length-i*.7),1);if(ia<=0)return;ctx.globalAlpha=ia;ctx.fillStyle=m.c+"44";ctx.strokeStyle=m.c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(mx,my,m.act?7:5.5,0,Math.PI*2);ctx.fill();ctx.stroke();if(m.act){const al=Math.log10(m.act),ay=sy+ch*(1-al/logM);ctx.strokeStyle=m.c;ctx.lineWidth=1.5;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(mx,my);ctx.lineTo(mx,ay);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=m.c;ctx.beginPath();ctx.arc(mx,ay,3.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle="#E8E2D9";ctx.font="bold 9px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText(m.n,mx,my-11);ctx.globalAlpha=1;});
    ctx.fillStyle="#00D9FF";ctx.fillRect(sx+cw-175,sy+8,10,10);ctx.fillStyle="#9D968E";ctx.font="9px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("Dense",sx+cw-162,sy+17);ctx.fillStyle="#10B981";ctx.fillRect(sx+cw-175,sy+24,10,10);ctx.fillText("MoE (dot=active params)",sx+cw-162,sy+33);
  },
  params:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const comps=[{n:"W_Q  (d²)",s:1,c:"#00D9FF"},{n:"W_K  (d²)",s:1,c:"#00D9FF88"},{n:"W_V  (d²)",s:1,c:"#00D9FFAA"},{n:"W_O  (d²)",s:1,c:"#00D9FF66"},{n:"FFN W1  (4d²)",s:4,c:"#10B981"},{n:"FFN W2  (4d²)",s:4,c:"#10B98188"},{n:"Norms (tiny)",s:.12,c:"#F0B84C"}];
    const total=11.12,sx=165,bh=22,g=5,y0=18;
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("Per-Layer Param Breakdown (proportional to d² units):",sx,y0-4);
    let cy=y0;
    comps.forEach((c,i)=>{const bw=(c.s/total)*(w-sx-16),ia=Math.min((t*.5-i*.1),1);if(ia<=0){cy+=bh+g;return;}ctx.globalAlpha=ia;ctx.fillStyle=c.c;ctx.fillRect(sx,cy,bw,bh-2);ctx.fillStyle="#E8E2D9";ctx.font="10px 'IBM Plex Mono'";ctx.textAlign="left";ctx.textBaseline="middle";ctx.fillText(c.n,16,cy+bh/2-1);ctx.textBaseline="alphabetic";ctx.globalAlpha=1;cy+=bh+g;});
    const fy=cy+8;rr(ctx,14,fy,w-28,36,7);ctx.fillStyle="rgba(240,184,76,.1)";ctx.fill();ctx.strokeStyle="#F0B84C";ctx.lineWidth=1.5;ctx.stroke();
    ctx.fillStyle="#F0B84C";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Total ≈ n_layers × 12 × d_model² + vocab × d_model",w/2,fy+18);ctx.textBaseline="alphabetic";
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";ctx.fillText("GPT-3: 96 × 12 × 12288² + 50K × 12288 ≈ 175B params",w/2,fy+44);
  },
  xent:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const vocab=["cat","dog","bird","fish","fox"],probs=[.65,.2,.08,.04,.03],sx=w*.2,maxW=w*.55,bh=26,g=5,sy=16;
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="left";ctx.fillText("Softmax output probabilities over vocabulary:",sx,sy-5);
    vocab.forEach((word,i)=>{const bw=probs[i]*maxW*Math.min(t,1),isT=i===0,y=sy+i*(bh+g);ctx.fillStyle=isT?"rgba(16,185,129,.13)":"rgba(0,217,255,.07)";ctx.fillRect(sx,y,maxW,bh);ctx.fillStyle=isT?"#10B981":"#00D9FF88";ctx.fillRect(sx,y,bw,bh);if(isT){ctx.strokeStyle="#10B981";ctx.lineWidth=1.8;ctx.strokeRect(sx,y,maxW,bh);}ctx.fillStyle="#E8E2D9";ctx.font="12px 'IBM Plex Mono'";ctx.textAlign="right";ctx.fillText(word,sx-8,y+bh/2+4);ctx.fillStyle="#D9D3CC";ctx.textAlign="right";ctx.fillText((probs[i]*100).toFixed(0)+"%",sx+maxW+42,y+bh/2+4);if(isT){ctx.fillStyle="#10B981";ctx.font="bold 9.5px 'IBM Plex Mono'";ctx.fillText("← TRUE",sx+maxW+82,y+bh/2+4);}});
    const la=Math.min(t-.6,1);if(la>0){ctx.globalAlpha=la;const loss=-Math.log(.65),fy=sy+vocab.length*(bh+g)+10;rr(ctx,sx,fy,maxW,36,7);ctx.fillStyle="rgba(240,184,76,.12)";ctx.fill();ctx.strokeStyle="#F0B84C";ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle="#F0B84C";ctx.font="bold 11px 'IBM Plex Mono'";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("L = -log(0.65) = "+loss.toFixed(3)+"  →  PPL = "+Math.exp(loss).toFixed(2),sx+maxW/2,fy+18);ctx.textBaseline="alphabetic";ctx.globalAlpha=1;}
  },
  roofline:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const sx=40,sy=20,cw=w-60,ch=h-50;
    ctx.strokeStyle="#3A342E";ctx.lineWidth=1;
    ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx,sy+ch);ctx.stroke();
    ctx.beginPath();ctx.moveTo(sx,sy+ch);ctx.lineTo(sx+cw,sy+ch);ctx.stroke();
    const rX = sx + cw*0.4;
    const rY = sy + ch*0.2;
    ctx.strokeStyle="#10B981";ctx.lineWidth=2;
    ctx.beginPath();ctx.moveTo(sx,sy+ch);ctx.lineTo(rX,rY);ctx.lineTo(sx+cw,rY);ctx.stroke();
    const pX = sx + cw*0.1 + (Math.sin(t*0.5)*0.5+0.5)*cw*0.7;
    const isBW = pX < rX;
    const pY = isBW ? sy+ch - ((pX-sx)/(rX-sx))*(ch*0.8) : rY;
    ctx.fillStyle="#00D9FF";ctx.beginPath();ctx.arc(pX,pY,6,0,Math.PI*2);ctx.fill();
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="center";
    ctx.fillText("Memory Bandwidth Bound", sx + cw*0.25, sy+ch*0.5);
    ctx.fillText("Compute Bound", sx + cw*0.7, rY+20);
    ctx.fillText("Operational Intensity (FLOPs/byte) →", sx+cw/2, sy+ch+20);
    ctx.save();ctx.translate(sx-15, sy+ch/2);ctx.rotate(-Math.PI/2);ctx.fillText("Performance",0,0);ctx.restore();
    ctx.fillStyle="#E8E2D9";ctx.fillText(isBW ? "Memory Bottleneck (Standard Attn)" : "Compute Bound (FlashAttention)", Math.max(sx+80, pX), pY-12);
  },
  specdecode:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const draftColor = "#00D9FF", targetColor = "#10B981", errorColor = "#E0705C";
    const ts = (t*0.8)%1;
    const sx = 30, tw=25, th=25, gap=8;
    ctx.fillStyle="#9D968E";ctx.font="10px 'Space Grotesk'";ctx.textAlign="left";
    ctx.fillText("Draft Model (Fast, auto-regressive):", sx, 25);
    ctx.fillText("Target Model (Slow, parallel verify):", sx, 95);
    const draftCount = 4;
    for(let i=0; i<draftCount; i++) {
        let alpha = ts > (i+1)*0.1 ? 1 : 0.2;
        ctx.fillStyle=draftColor; ctx.globalAlpha=alpha*0.3;
        rr(ctx, sx+i*(tw+gap), 35, tw, th, 4); ctx.fill();
        ctx.globalAlpha=alpha; ctx.fillStyle=draftColor; ctx.font="10px 'IBM Plex Mono'";
        ctx.fillText("t"+(i+1), sx+i*(tw+gap)+5, 52);
    }
    ctx.globalAlpha=1;
    if (ts > 0.6) {
        ctx.fillStyle=targetColor; ctx.globalAlpha=0.2;
        rr(ctx, sx, 105, draftCount*(tw+gap)-gap, th+10, 4); ctx.fill();
        ctx.globalAlpha=1; ctx.strokeStyle=targetColor; ctx.strokeRect(sx, 105, draftCount*(tw+gap)-gap, th+10);
        ctx.fillStyle=targetColor; ctx.fillText("Parallel Forward Pass", sx+5, 125);
        if (ts > 0.8) {
           const lx = sx+(draftCount-1)*(tw+gap);
           ctx.fillStyle=errorColor; ctx.globalAlpha=0.5; rr(ctx, lx, 105, tw, th+10, 4); ctx.fill();
           ctx.globalAlpha=1; ctx.fillStyle="#fff"; ctx.fillText("X", lx+8, 125);
           ctx.fillStyle=targetColor;
           rr(ctx, lx+tw+gap, 105, tw, th+10, 4); ctx.fill();
           ctx.fillStyle="#000"; ctx.fillText("✓", lx+tw+gap+8, 125);
        }
    }
    ctx.fillStyle="#9D968E";ctx.font="9.5px 'Space Grotesk'";ctx.textAlign="center";
    ctx.fillText("Generate K tokens quickly, verify all K in 1 step.", w/2, h-10);
  },
  sae:(ctx,w,h,t)=>{
    ctx.clearRect(0,0,w,h);
    const sx=w*0.15, dw=w*0.7;
    const y1=h*0.25, y3=h*0.7;
    ctx.fillStyle="#9D968E";ctx.font="11px 'Space Grotesk'";ctx.textAlign="center";
    ctx.fillText("Polysemantic Neuron (Dense)", w/2, y1-25);
    ctx.fillText("Monosemantic Features (Sparse Autoencoder)", w/2, y3+25);
    ctx.fillStyle="rgba(0,217,255,0.2)"; ctx.strokeStyle="#00D9FF";
    ctx.beginPath();ctx.arc(w/2, y1, 15, 0, Math.PI*2);ctx.fill();ctx.stroke();
    const nF = 5;
    const ts = (Math.sin(t*2)*0.5+0.5);
    const activeIdx = Math.floor((t*0.5)%nF);
    for(let i=0; i<nF; i++) {
       const fx = sx + i*(dw/(nF-1));
       const isActive = (i === activeIdx || i === (activeIdx+2)%nF);
       const alpha = isActive ? (0.2 + 0.8*ts) : 0.1;
       ctx.strokeStyle=`rgba(16,185,129,${alpha*0.5})`; ctx.lineWidth=1;
       ctx.beginPath();ctx.moveTo(w/2, y1+15);ctx.lineTo(fx, y3-15);ctx.stroke();
       ctx.fillStyle=`rgba(16,185,129,${alpha})`;
       ctx.beginPath();ctx.arc(fx, y3, 10, 0, Math.PI*2);ctx.fill();
       if (isActive) {
           ctx.fillStyle="#10B981"; ctx.font="9px 'IBM Plex Mono'";
           ctx.fillText(i===activeIdx ? "DNA" : "Code", fx, y3-15);
       }
    }
  }
,
  anim_causal_mask: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2 - 60, h/2 - 60);
    const size = 120, cells = 8, cs = size/cells;
    ctx.strokeStyle = 'rgba(255,255,255,0.1)';
    ctx.lineWidth = 1;
    for(let i=0; i<cells; i++){
      for(let j=0; j<cells; j++){
        if(j > i) {
          ctx.fillStyle = 'rgba(224,112,92,'+(0.1 + Math.sin(t*2)*0.05)+')'; // masked
        } else {
          ctx.fillStyle = 'rgba(16,185,129,'+(0.2 + (i===cells-1 && j===Math.floor((t*4)%cells) ? 0.5 : 0))+')'; // active
        }
        ctx.fillRect(j*cs, i*cs, cs-1, cs-1);
        ctx.strokeRect(j*cs, i*cs, cs-1, cs-1);
      }
    }
    ctx.fillStyle = 'white'; ctx.font = '10px monospace';
    ctx.fillText('-inf', size + 10, 20);
    ctx.beginPath(); ctx.moveTo(size+5, 15); ctx.lineTo(size/2 + 20, size/4 - 10); ctx.strokeStyle = 'red'; ctx.stroke();
  },
  anim_mha_split: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2, h/2);
    ctx.fillStyle = '#00D9FF';
    ctx.fillRect(-80, -20, 30, 40); // QKV
    ctx.fillStyle = 'white'; ctx.font = '12px monospace'; ctx.fillText('QKV', -75, 5);
    
    for(let i=0; i<4; i++) {
      let y = -45 + i*30;
      ctx.fillStyle = ['#E0705C','#10B981','#F0B84C','#8B5CF6'][i];
      ctx.fillRect(-10, y, 20, 20); // Head
      
      // Lines
      ctx.beginPath();
      ctx.moveTo(-50, 0); ctx.lineTo(-30, y+10); ctx.lineTo(-10, y+10);
      ctx.moveTo(10, y+10); ctx.lineTo(30, y+10); ctx.lineTo(50, 0);
      ctx.strokeStyle = 'rgba(255,255,255,0.3)';
      if(t*3 % 4 >= i && t*3 % 4 < i+1) ctx.strokeStyle = 'white';
      ctx.stroke();
    }
    ctx.fillStyle = '#00D9FF';
    ctx.fillRect(50, -20, 30, 40); // Concat
    ctx.fillStyle = 'white'; ctx.fillText('Out', 55, 5);
  },
  anim_gqa: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2 - 50, h/2);
    // Q heads (8)
    for(let i=0; i<8; i++){
      let y = -75 + i*20;
      ctx.fillStyle = '#E0705C';
      ctx.fillRect(-40, y, 15, 15);
      
      // KV heads (2 groups, so 4 Qs share 1 KV)
      let g = Math.floor(i/4);
      let kvy = -25 + g*60;
      
      ctx.beginPath();
      ctx.moveTo(-25, y+7.5);
      ctx.lineTo(20, kvy+10);
      ctx.strokeStyle = 'rgba(255,255,255,'+(0.1 + Math.sin(t*3 - i*0.5)*0.2 + 0.2)+')';
      ctx.stroke();
    }
    
    // KV pairs
    for(let i=0; i<2; i++){
      let kvy = -25 + i*60;
      ctx.fillStyle = '#10B981'; ctx.fillRect(20, kvy, 15, 20); // K
      ctx.fillStyle = '#F0B84C'; ctx.fillRect(37, kvy, 15, 20); // V
    }
    ctx.fillStyle='white'; ctx.font='11px sans-serif';
    ctx.fillText('8 Q Heads', -45, 95);
    ctx.fillText('2 KV Groups', 10, 95);
  },
  anim_cross_attn: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2, h/2);
    // Text Q
    ctx.fillStyle = '#E0705C'; ctx.fillRect(-60, -20, 30, 40);
    ctx.fillStyle = 'white'; ctx.font = '12px sans-serif'; ctx.fillText('Q (Text)', -65, 35);
    
    // Image KV
    ctx.fillStyle = '#10B981'; ctx.fillRect(30, -30, 20, 60);
    ctx.fillStyle = '#F0B84C'; ctx.fillRect(52, -30, 20, 60);
    ctx.fillStyle = 'white'; ctx.fillText('K, V (Image)', 25, 45);
    
    // Beams
    ctx.beginPath();
    ctx.moveTo(-30, 0); ctx.lineTo(30, Math.sin(t*4)*20);
    ctx.strokeStyle = 'rgba(224,112,92,0.8)';
    ctx.lineWidth = 2;
    ctx.stroke();
  },
  anim_sparse_window: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2 - 40, h/2 - 40);
    const size = 80, cells = 10, cs = size/cells;
    ctx.strokeStyle = 'rgba(255,255,255,0.1)'; ctx.lineWidth = 1;
    for(let i=0; i<cells; i++){
      for(let j=0; j<cells; j++){
        ctx.strokeRect(j*cs, i*cs, cs-1, cs-1);
        let dist = Math.abs(i - j);
        let active = dist <= 1 || j === 0 || i === 0; // sliding window + global token at 0
        if(active) {
          ctx.fillStyle = 'rgba(16,185,129,'+(0.3 + Math.sin(t*3 + i*0.5)*0.2)+')';
          ctx.fillRect(j*cs, i*cs, cs-1, cs-1);
        }
      }
    }
    ctx.fillStyle = 'white'; ctx.font='11px sans-serif';
    ctx.fillText('O(n * w) active', -5, size + 20);
  },
  anim_linear_kernel: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2, h/2);
    // O(n^2) visual
    ctx.fillStyle = 'rgba(224,112,92,0.3)';
    ctx.strokeStyle = '#E0705C';
    let s1 = 40 + Math.sin(t*2)*5;
    ctx.fillRect(-60-s1/2, -s1/2, s1, s1);
    ctx.strokeRect(-60-s1/2, -s1/2, s1, s1);
    ctx.fillStyle = 'white'; ctx.font = '11px sans-serif'; ctx.fillText('O(n²)', -75, s1/2 + 15);
    
    // O(n) visual
    ctx.fillStyle = 'rgba(16,185,129,0.3)';
    ctx.strokeStyle = '#10B981';
    let w2 = 10, h2 = 40;
    ctx.fillRect(40-w2/2, -h2/2, w2, h2);
    ctx.strokeRect(40-w2/2, -h2/2, w2, h2);
    ctx.fillStyle = 'white'; ctx.fillText('O(n)', 30, h2/2 + 15);
    
    ctx.fillText('vs', -5, 5);
  },
  anim_flash_tiling: (ctx,w,h,t) => {
    ctx.clearRect(0,0,w,h);
    ctx.translate(w/2, h/2);
    
    // Main Memory (HBM)
    ctx.strokeStyle = 'rgba(255,255,255,0.2)';
    ctx.strokeRect(-80, -60, 60, 120);
    ctx.fillStyle = 'rgba(255,255,255,0.5)'; ctx.font = '10px sans-serif'; ctx.fillText('GPU HBM', -70, -65);
    
    // SRAM (Fast cache)
    ctx.strokeStyle = '#F0B84C';
    ctx.strokeRect(20, -20, 60, 40);
    ctx.fillStyle = '#F0B84C'; ctx.fillText('SRAM', 35, -25);
    
    // Tiles moving
    let tileY = -50 + ((t*40)%100);
    if(tileY > 50) tileY = -50;
    
    ctx.fillStyle = '#10B981';
    ctx.fillRect(-70, tileY, 40, 15); // Tile in HBM
    
    // Transfer line
    ctx.beginPath(); ctx.moveTo(-30, tileY+7.5); ctx.lineTo(20, 0); 
    ctx.strokeStyle = 'rgba(16,185,129,'+Math.max(0, 1 - Math.abs(tileY)/50)+')';
    ctx.lineWidth = 2; ctx.stroke();
    
    ctx.fillRect(30, -10, 40, 20); // Tile in SRAM
  }
};
