// AUTO-GENERATED by scripts/generate-atlas-content.mjs — do not edit by hand.
// Source: scripts/vendor/atlas-logic.js

import type { AtlasMeta } from './types'

export const ATLAS_META: AtlasMeta[] = [
  {
    "id": "attn-variants",
    "label": "Attention Variations",
    "title": "The Evolution of Attention",
    "color": "#FF6B6B",
    "icon": "🔀",
    "subCount": 7,
    "wordCount": 677,
    "figureCount": 7,
    "equationCount": 7
  },
  {
    "id": "math-primer",
    "label": "Math Basics",
    "title": "Math Primer",
    "color": "#F7B731",
    "icon": "🧮",
    "subCount": 4,
    "wordCount": 226,
    "figureCount": 0,
    "equationCount": 5
  },
  {
    "id": "foundations",
    "label": "01 — Foundations",
    "title": "What Is a Language Model?",
    "color": "#6C63FF",
    "icon": "📐",
    "subCount": 9,
    "wordCount": 817,
    "figureCount": 3,
    "equationCount": 9
  },
  {
    "id": "pre2017",
    "label": "02 — Before 2017",
    "title": "The Pre-Transformer Era",
    "color": "#FF6B6B",
    "icon": "🕰️",
    "subCount": 8,
    "wordCount": 804,
    "figureCount": 6,
    "equationCount": 13
  },
  {
    "id": "transformer",
    "label": "03 — The Transformer",
    "title": "Attention Is All You Need (2017)",
    "color": "#00C9A7",
    "icon": "⚡",
    "subCount": 12,
    "wordCount": 1411,
    "figureCount": 9,
    "equationCount": 17
  },
  {
    "id": "clusterA",
    "label": "04 — Dense Transformers",
    "title": "Cluster A: Quadratic Attention O(n²)",
    "color": "#F7B731",
    "icon": "🧱",
    "subCount": 10,
    "wordCount": 1231,
    "figureCount": 4,
    "equationCount": 9
  },
  {
    "id": "clusterB",
    "label": "05 — Linear & Recurrent",
    "title": "Cluster B: Sub-Quadratic O(n)",
    "color": "#A29BFE",
    "icon": "🌊",
    "subCount": 6,
    "wordCount": 750,
    "figureCount": 4,
    "equationCount": 9
  },
  {
    "id": "alt",
    "label": "06 — Alternative Architectures",
    "title": "Beyond the Transformer Stack",
    "color": "#6C63FF",
    "icon": "🛸",
    "subCount": 3,
    "wordCount": 333,
    "figureCount": 0,
    "equationCount": 2
  },
  {
    "id": "tokenizers",
    "label": "07 — Tokenizers",
    "title": "Tokenizer Evolution",
    "color": "#00B894",
    "icon": "✂️",
    "subCount": 6,
    "wordCount": 743,
    "figureCount": 4,
    "equationCount": 5
  },
  {
    "id": "training",
    "label": "08 — Training & Hardware",
    "title": "Activations, Optimizers & Systems",
    "color": "#FDCB6E",
    "icon": "🧪",
    "subCount": 6,
    "wordCount": 870,
    "figureCount": 4,
    "equationCount": 9
  },
  {
    "id": "infer",
    "label": "09 — Inference & Deployment",
    "title": "Serving at Scale",
    "color": "#0984E3",
    "icon": "🚀",
    "subCount": 3,
    "wordCount": 285,
    "figureCount": 1,
    "equationCount": 0
  },
  {
    "id": "gaps",
    "label": "10 — Critical Gaps & Scaling",
    "title": "What Remains Unsolved",
    "color": "#E17055",
    "icon": "⚠️",
    "subCount": 7,
    "wordCount": 942,
    "figureCount": 5,
    "equationCount": 6
  },
  {
    "id": "scaling",
    "label": "11 — Scaling Laws",
    "title": "The Economics of Scale",
    "color": "#74B9FF",
    "icon": "📈",
    "subCount": 3,
    "wordCount": 388,
    "figureCount": 3,
    "equationCount": 6
  },
  {
    "id": "implications",
    "label": "12 — Implications",
    "title": "What It Means & Where It's Going",
    "color": "#55EFC4",
    "icon": "🔭",
    "subCount": 2,
    "wordCount": 318,
    "figureCount": 0,
    "equationCount": 1
  }
]
