// AUTO-GENERATED by scripts/generate-atlas-content.mjs — do not edit by hand.
// Source: scripts/vendor/atlas-logic.js

import type { AtlasSection } from './types'

export const ATLAS_SECTIONS: AtlasSection[] = [
  {
    "id": "attn-variants",
    "label": "Attention Variations",
    "title": "The Evolution of Attention",
    "color": "#FF6B6B",
    "icon": "🔀",
    "subs": [
      {
        "id": "causal_attn",
        "title": "1. The \"Looking Forward\" Change (Causal / Masked Attention)",
        "body": "**Used in:** GPT, Llama, Mistral (decoder-only models).\n\n**The Math Change:** Before the Softmax step, we add a mask (a matrix of negative infinity) to the top-right half of the scores.\n\n**Simple Explanation:** When predicting the next word, the model is forbidden from \"peeking\" at future words. The math forces the percentages for any future token to become exactly **0%**. It only pays attention to the words that came *before* the current one.",
        "anim": "anim_causal_mask",
        "math": {
          "eqs": [
            {
              "l": "Causal Masked Attention",
              "t": "\\text{Attention}(Q,K,V) = \\text{Softmax}\\left(\\frac{QK^T + M}{\\sqrt{d_k}}\\right)V"
            }
          ]
        }
      },
      {
        "id": "mha_revisited",
        "title": "2. The \"Multiple Perspectives\" Change (Multi-Head Attention)",
        "body": "**Used in:** Original Transformer, early GPTs.\n\n**The Math Change:** Instead of doing the core formula once, we split Q, K, and V into multiple smaller chunks (heads). We run the exact same formula independently on each chunk, then glue (concatenate) the results together.\n\n**Simple Explanation:** One head might focus on grammar (verbs/objects), while another focuses on pronouns, and another focuses on context. Running the math in parallel lets the model capture different \"relationships\" at the same time.",
        "anim": "anim_mha_split",
        "math": {
          "eqs": [
            {
              "l": "Multi-Head Attention",
              "t": "\\text{MHA}(Q,K,V) = \\text{Concat}(\\text{head}_1, \\dots, \\text{head}_h)W^O"
            }
          ]
        }
      },
      {
        "id": "gqa_attn",
        "title": "3. The \"Memory Saver\" Change (Multi-Query & GQA)",
        "body": "**Used in:** Llama 2/3, PaLM.\n\n**The Math Change:** Instead of having unique K and V for every attention head, multiple Q heads are forced to share the *same* K and V.\n\n**Simple Explanation:** The math stays identical, but we dramatically shrink the size of the K and V matrices. This means the model uses far less memory when generating text, allowing it to run much faster, at a tiny cost to its \"focus\" diversity.",
        "anim": "anim_gqa",
        "math": {
          "eqs": [
            {
              "l": "Grouped-Query sharing",
              "t": "K_i = K_{\\lfloor i/g \\rfloor}, \\quad V_i = V_{\\lfloor i/g \\rfloor}"
            }
          ]
        }
      },
      {
        "id": "cross_attn",
        "title": "4. The \"Cross-Modal\" Change (Cross-Attention)",
        "body": "**Used in:** Image-to-text models, translation (old Transformers), stable diffusion.\n\n**The Math Change:** The **Q** comes from one source (e.g., the text you are generating), but the **K** and **V** come from a completely different source (e.g., the image pixels or the foreign-language sentence).\n\n**Simple Explanation:** You are asking a question (Q) about a specific database of facts (K, V). The math doesn't change, but *where the numbers come from* changes entirely. It lets a model read a document and answer questions about it.",
        "anim": "anim_cross_attn",
        "math": {
          "eqs": [
            {
              "l": "Cross-Attention",
              "t": "\\text{Attention}(Q_{text}, K_{image}, V_{image})"
            }
          ]
        }
      },
      {
        "id": "sparse_attn",
        "title": "5. The \"Sparse\" Change (Sliding Window & Global)",
        "body": "**Used in:** Longformer, Mistral 7B, BigBird.\n\n**The Math Change:** Instead of calculating $QK^T$ for *every single token* in a 10,000-word document (which is mathematically $O(n^2)$ and impossibly slow), we force the scores for far-away tokens to be zero. We only calculate the dot product for local neighbors (sliding window) and a few special \"global\" tokens.\n\n**Simple Explanation:** Instead of comparing every word to every other word (which is math-heavy), we tell the model: \"Only look at the words right next to you, plus a few main topic words.\" The math is the same, but we skip 95% of the calculations to handle huge documents.",
        "anim": "anim_sparse_window",
        "math": {
          "eqs": [
            {
              "l": "Sparse Complexity",
              "t": "O(n \\times w) \\ll O(n^2)"
            }
          ]
        }
      },
      {
        "id": "linear_attn",
        "title": "6. The \"Order of Operations\" Change (Linear/Kernel)",
        "body": "**Used in:** Performer, RWKV (partially), some efficient models.\n\n**The Math Change:** This is a *big* math trick. Normally, you do $(Q \\times K^T) \\times V$. Mathematically, this forces you to build a massive matrix. Linear attention uses a math property called the **kernel trick**. It replaces the dot-product with a special function (like $\\text{elu}(x)+1$) so that you can rewrite the math as $Q \\times (K^T \\times V)$.\n\n**Simple Explanation:** By changing the order you multiply the numbers, you never have to build the giant \"similarity matrix.\" This drops the math workload from $O(n^2)$ down to $O(n)$ (linear). The trade-off is that it loses some precision on very long sequences, but it is lightning-fast.",
        "anim": "anim_linear_kernel",
        "math": {
          "eqs": [
            {
              "l": "Associativity Trick",
              "t": "(Q K^T) V \\rightarrow Q (K^T V)"
            }
          ]
        }
      },
      {
        "id": "flash_attn",
        "title": "7. The \"Hardware\" Change (Flash Attention)",
        "body": "**Used in:** Almost *every* modern model (GPT-4, Llama 3, Mistral).\n\n**The Math Change:** **Here is the secret: Flash Attention does NOT change the math formula at all.** It calculates $\\text{Softmax}(QK^T)V$ to the exact decimal as the original formula.\n\n**Simple Explanation:** Instead of calculating all the scores, writing them to temporary memory, reading them back, and then doing Softmax, Flash Attention does the math in tiny overlapping chunks (tiling) directly inside the GPU's super-fast cache memory (SRAM). It uses smart math (online softmax) to stitch these chunks together. The result is the *exact same answer*, but it runs 2x–10x faster and uses far less memory.",
        "anim": "anim_flash_tiling",
        "math": {
          "eqs": [
            {
              "l": "Tiling & Online Softmax",
              "t": "\\tilde{m}_{ij} = \\max(m_i, m_j), \\quad \\tilde{l}_{ij} = e^{m_i - \\tilde{m}_{ij}}l_i + e^{m_j - \\tilde{m}_{ij}}l_j"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "math-primer",
    "label": "Math Basics",
    "color": "#F7B731",
    "subs": [
      {
        "id": "math-vectors",
        "title": "Vectors and Matrices",
        "body": "A vector is an array of numbers, representing a point or direction in space. LLMs represent everything—words, images, concepts—as high-dimensional vectors (e.g., 4096 dimensions). A matrix is a 2D grid of numbers that transforms these vectors. When a token passes through a Transformer layer, it is repeatedly multiplied by matrices (weights) to update its meaning.",
        "math": {
          "eqs": [
            {
              "l": "Vector",
              "t": "\\mathbf{v} = [v_1, v_2, ..., v_d] \\in \\mathbb{R}^d"
            },
            {
              "l": "Matrix Multiplication",
              "t": "\\mathbf{y} = \\mathbf{W}\\mathbf{x} + \\mathbf{b}"
            }
          ]
        }
      },
      {
        "id": "math-dot-product",
        "title": "Dot Product (Similarity)",
        "body": "The dot product measures how aligned two vectors are. In attention mechanisms, we compute the dot product between a \"query\" vector (what a word is looking for) and a \"key\" vector (what another word offers). A higher dot product means the words are more relevant to each other in context.",
        "math": {
          "eqs": [
            {
              "l": "Dot Product",
              "t": "\\mathbf{q} \\cdot \\mathbf{k} = \\sum_{i=1}^{d} q_i k_i = ||\\mathbf{q}|| ||\\mathbf{k}|| \\cos(\\theta)"
            }
          ]
        }
      },
      {
        "id": "math-softmax",
        "title": "Softmax Function",
        "body": "The softmax function takes a list of raw scores (logits) and squashes them into probabilities that sum to 1. In LLMs, it is used twice: first in the attention mechanism to determine how much \"weight\" to give each surrounding word, and second at the very end to output the probability of the next token.",
        "math": {
          "eqs": [
            {
              "l": "Softmax",
              "t": "\\text{Softmax}(x_i) = \\frac{e^{x_i}}{\\sum_j e^{x_j}}"
            }
          ]
        }
      },
      {
        "id": "math-gradients",
        "title": "Gradients and Derivatives",
        "body": "A derivative measures how much the output of a function changes if you slightly tweak the input. A gradient is simply a vector of derivatives for multiple variables. During training, backpropagation computes the gradient of the loss with respect to every single parameter, telling the optimizer exactly how to adjust the weights to improve the model.",
        "math": {
          "eqs": [
            {
              "l": "Gradient Update",
              "t": "\\theta_{new} = \\theta_{old} - \\eta \\nabla_{\\theta} L(\\theta)"
            }
          ]
        }
      }
    ],
    "title": "Math Primer",
    "icon": "🧮"
  },
  {
    "id": "foundations",
    "label": "01 — Foundations",
    "title": "What Is a Language Model?",
    "color": "#6C63FF",
    "icon": "📐",
    "subs": [
      {
        "id": "lm",
        "title": "Language Model",
        "body": "A language model is a system that assigns probabilities to sequences of tokens. Given some text so far, it predicts what comes next — formally learning P(next token | previous tokens).\n\nIf you have ever used phone keyboard autocomplete, you have used a language model. The 'knowledge' is statistical: the model has seen enormous amounts of text and learned which continuations tend to follow which inputs. It does not reason in the human sense; it interpolates over patterns.",
        "anim": "token_pred",
        "math": {
          "eqs": [
            {
              "l": "Chain Rule of Probability",
              "t": "P(w_1,...,w_n) = \\prod_i P(w_i | w_1,...,w_{i-1})"
            }
          ]
        }
      },
      {
        "id": "llm",
        "title": "Large Language Model",
        "body": "'Large' refers chiefly to the number of parameters (the tunable numbers inside the model — think of them as adjustable knobs) and the volume of training data.\n\nA small language model might have millions of parameters; an LLM has billions to over a trillion. GPT-1 (2018) had 117 million; GPT-3 (2020) had 175 billion — a 1500× jump in two years.\n\nBeyond certain thresholds, qualitatively new behaviors appear ('emergent abilities') — such as solving math problems or writing code that were never explicitly trained. This threshold effect is still debated and not fully understood.",
        "anim": "param_scale",
        "math": {
          "eqs": [
            {
              "l": "Parameter Space",
              "t": "\\theta \\in \\mathbb{R}^N, \\, N \\approx 10^9 \\text{ to } 10^{12}"
            }
          ]
        }
      },
      {
        "id": "phases",
        "title": "Pre-training → Fine-tuning → Inference",
        "body": "Pre-training: the massive, expensive first phase where the model learns general language patterns from a huge corpus — trillions of tokens. Virtually all the model's 'knowledge' is acquired here. A single pre-training run for a frontier model can cost tens of millions of dollars.\n\nFine-tuning: a smaller, cheaper later phase that adapts the pre-trained model to specific behaviors — e.g., following instructions (SFT), being helpful and harmless (RLHF/DPO), or answering in a specific domain.\n\nInference: using the trained model to produce outputs for users. No learning happens; parameters are frozen. The cost is per generated token, paid every time someone uses the model.",
        "anim": "phases",
        "math": {
          "eqs": [
            {
              "l": "1. Pre-training",
              "t": "L_{PT} = -\\log P(x_t | x_{<t})"
            },
            {
              "l": "2. SFT",
              "t": "L_{SFT} = -\\sum_{t} \\log P(y_t | x, y_{<t})"
            },
            {
              "l": "3. RLHF",
              "t": "\\max_\\pi \\mathbb{E}[R(x, y)] - \\beta D_{KL}(\\pi || \\pi_{ref})"
            }
          ]
        }
      },
      {
        "id": "misconceptions",
        "title": "Common Misconceptions",
        "body": "• 'LLM = ChatGPT' — ChatGPT is one product built on top of GPT-series LLMs plus fine-tuning and a chat interface. LLMs are a broad class of models from many organizations.\n\n• 'Transformer = LLM' — The Transformer is an architecture; an LLM is a large model trained on language. Vision Transformers exist and are not LLMs. An LLM could in principle use a non-Transformer architecture (Mamba-based models exist).\n\n• 'More parameters = better' — Chinchilla (2022) showed many large models were badly under-trained. A 70B model trained on 1.4T tokens can beat a 175B model trained on only 300B tokens.\n\n• 'Context window = usable context' — RULER (2024) showed models claiming 128K context windows often fail functionally at 32K on multi-hop retrieval tasks."
      },
      {
        "id": "vectors",
        "title": "Vectors & Dot Products",
        "body": "At their core, neural networks process numbers, not text. A vector is a list of numbers representing a point in high-dimensional space. Words are converted into 'embeddings' — vectors where semantic similarity correlates with geometric proximity.\n\nThe dot product measures similarity: it's the projection of one vector onto another. A high positive dot product means the vectors point in similar directions (similar meaning), while near-zero means they are orthogonal (unrelated). This simple operation is the mathematical engine behind attention and embeddings.",
        "math": {
          "eqs": [
            {
              "l": "Dot Product",
              "t": "\\mathbf{u} \\cdot \\mathbf{v} = \\sum_{i=1}^n u_i v_i = |\\mathbf{u}| |\\mathbf{v}| \\cos\\theta"
            }
          ]
        }
      },
      {
        "id": "grad_desc",
        "title": "Gradient Descent & Backpropagation",
        "body": "How do models learn? Imagine standing on a foggy mountain and wanting to reach the valley (minimum error). Gradient descent means taking a step in the direction of the steepest downward slope.\n\nBackpropagation calculates this slope efficiently. It applies the chain rule of calculus backwards through the network layers to assign 'blame' for the final error to every single parameter, allowing the model to update billions of weights simultaneously.",
        "math": {
          "eqs": [
            {
              "l": "Weight Update",
              "t": "W \\leftarrow W - \\eta \\frac{\\partial L}{\\partial W}"
            }
          ]
        }
      },
      {
        "id": "neuron",
        "title": "Neurons & Layers",
        "body": "A single artificial neuron takes multiple inputs, multiplies each by a learned weight, sums them up, and applies a non-linear activation function. It acts as a pattern detector.\n\nA layer is a collection of these neurons acting in parallel. Deep learning stacks these layers: early layers detect simple features (like word frequency), while deeper layers compose them into complex concepts (like sarcasm or logical entailment).",
        "math": {
          "eqs": [
            {
              "l": "Neuron output",
              "t": "y = \\sigma\\left(\\sum_{i=1}^n w_i x_i + b\\right)"
            }
          ]
        }
      },
      {
        "id": "sampling",
        "title": "Temperature & Sampling",
        "body": "Language models output a probability distribution over the entire vocabulary for the next token. How do we pick one?\n\nGreedy decoding always picks the most likely token, which can lead to repetitive, robotic text.\nSampling picks randomly according to the probabilities. Temperature (T) scales these probabilities: T=1 is the original distribution. T < 1 makes the model more confident and deterministic. T > 1 flattens the distribution, increasing randomness and creativity but risking incoherence.\nNucleus Sampling (Top-p) restricts the choice to the smallest set of top tokens whose cumulative probability exceeds p, dynamically trimming the 'long tail' of gibberish.",
        "math": {
          "eqs": [
            {
              "l": "Temperature Scaling",
              "t": "p_i = \\frac{\\exp(z_i / T)}{\\sum_j \\exp(z_j / T)}"
            }
          ]
        }
      },
      {
        "id": "tok_cost",
        "title": "Tokenization vs Inference Cost",
        "body": "Processing text costs compute. Tokenization is the fast O(N) process of chunking text into IDs using a fixed dictionary. It takes microseconds on a CPU.\n\nInference is the O(N^2) forward pass through billions of parameters on a GPU. The cost of generating a token is astronomically higher than tokenizing it. This is why LLM pricing is measured in 'per 1M tokens' processed by the model, ignoring the negligible cost of the tokenizer itself."
      }
    ]
  },
  {
    "id": "pre2017",
    "label": "02 — Before 2017",
    "title": "The Pre-Transformer Era",
    "color": "#FF6B6B",
    "icon": "🕰️",
    "subs": [
      {
        "id": "ngrams",
        "title": "N-Gram Language Models",
        "body": "N-gram models estimate the probability of a word given the previous n−1 words by counting occurrences in a corpus. A bigram model uses the count of adjacent pairs divided by the count of the first word.\n\nThey are simple, fast, and interpretable — but suffer from data sparsity (most long n-grams are never seen in training) and cannot capture dependencies beyond n-1 words. A 5-gram model literally cannot learn that the subject of a sentence determines the verb 20 words later.\n\nThese were the dominant approach in speech recognition and machine translation through the 2000s.",
        "anim": "ngram",
        "math": {
          "eqs": [
            {
              "l": "Bigram probability",
              "t": "P(w_i \\mid w_{i-1}) = \\dfrac{\\text{count}(w_{i-1},\\, w_i)}{\\text{count}(w_{i-1})}"
            }
          ]
        }
      },
      {
        "id": "w2v",
        "title": "Word Embeddings: Word2Vec & GloVe",
        "body": "Word2Vec (Mikolov et al., 2013) learns dense vectors for words such that similar words land near each other in embedding space. The skip-gram variant predicts surrounding context words from a target word using softmax over dot products.\n\nGloVe (Pennington et al., 2014) factorizes a global co-occurrence matrix: it learns vectors whose dot products approximate the log co-occurrence frequency.\n\nKey result: linear algebra on vectors encodes semantic relationships — the famous 'king − man + woman ≈ queen' vector arithmetic.\n\nCritical limitation: these are context-invariant — the word 'bank' gets one fixed vector regardless of whether it means riverbank or financial institution. This was the core flaw that contextual models (ELMo, BERT) later fixed.",
        "anim": "w2v",
        "math": {
          "eqs": [
            {
              "l": "Skip-gram objective",
              "t": "P(c \\mid t) \\propto \\exp(\\mathbf{v}_c \\cdot \\mathbf{v}_t)"
            },
            {
              "l": "GloVe objective",
              "t": "J = \\textstyle\\sum_{i,j} f(X_{ij})\\,(\\mathbf{v}_i^\\top \\mathbf{v}_j - \\log X_{ij})^2"
            }
          ]
        }
      },
      {
        "id": "hmm_crf",
        "title": "HMMs & CRFs",
        "body": "Before deep learning, sequence labeling (like finding names in text) relied on statistical graphical models.\n\nHidden Markov Models (HMMs) model a sequence of hidden states (like parts of speech) that probabilistically emit the observed words. They are generative.\nConditional Random Fields (CRFs) model the conditional probability of the state sequence directly given the observations. They are discriminative and handle overlapping features much better than HMMs, becoming the gold standard for NLP until neural networks took over.",
        "math": {
          "eqs": [
            {
              "l": "HMM Joint Prob",
              "t": "P(X,Y) = \\prod_{t=1}^T P(y_t|y_{t-1}) P(x_t|y_t)"
            }
          ]
        }
      },
      {
        "id": "elmo",
        "title": "ELMo: Contextual Embeddings (2018)",
        "body": "Embeddings from Language Models (ELMo, Peters et al.) fixed the fatal flaw of Word2Vec: context-independence.\n\nInstead of a static dictionary lookup, ELMo runs a bidirectional LSTM over the entire sentence. The vector for the word 'bank' is dynamically constructed based on the surrounding words. This was a massive leap forward, proving that pre-training deep language models on unlabeled text creates representations that drastically improve downstream tasks."
      },
      {
        "id": "rnn",
        "title": "RNNs & The Vanishing Gradient Problem",
        "body": "An RNN processes a sequence one element at a time, maintaining a hidden state h_t that summarizes everything seen so far. The same weight matrix W_h is reused at every step.\n\nThe vanishing gradient problem: during backpropagation, gradients are propagated backward through every time step. Each step multiplies by the Jacobian of the state transition — essentially by W_h repeatedly. If the largest eigenvalue of W_h is less than 1, the product of T such matrices shrinks exponentially toward zero. The network literally cannot 'feel' what happened far back in the sequence.\n\nIf the eigenvalue exceeds 1, gradients explode — causing unstable training (addressed by gradient clipping, but the expressiveness limit remains).",
        "anim": "rnn",
        "math": {
          "eqs": [
            {
              "l": "RNN state update",
              "t": "h_t = \\sigma(W_h \\cdot h_{t-1} + W_x \\cdot x_t + b)"
            },
            {
              "l": "Vanishing gradient",
              "t": "\\frac{\\partial L}{\\partial h_0} = \\frac{\\partial L}{\\partial h_T} \\prod_{t=1}^{T} W_h \\xrightarrow[T\\to\\infty]{} 0"
            }
          ]
        }
      },
      {
        "id": "lstm",
        "title": "LSTMs & GRUs — Gating the Memory",
        "body": "LSTMs (Hochreiter & Schmidhuber, 1997) add a cell state and three gates — forget, input, and output — that regulate information flow. Each gate uses a sigmoid function σ(x) = 1/(1+e^{-x}) outputting a value in [0,1]: 0 means 'block everything', 1 means 'pass everything'.\n\nThe crucial trick: the cell state is updated additively (C_t = f_t ⊙ C_{t-1} + i_t ⊙ C̃_t). Addition means the gradient of the loss with respect to C_{t-1} flows back as just f_t — not a full matrix multiplication — so gradients travel much further back in time without vanishing.\n\nGRUs (Cho et al., 2014) simplify to two gates (reset and update), offering comparable quality at lower computational cost.",
        "anim": "lstm",
        "math": {
          "eqs": [
            {
              "l": "Forget gate",
              "t": "f_t = \\sigma(W_f [h_{t-1}, x_t] + b_f)"
            },
            {
              "l": "Cell update (additive)",
              "t": "C_t = f_t \\odot C_{t-1} + i_t \\odot \\tilde{C}_t"
            },
            {
              "l": "Output",
              "t": "h_t = o_t \\odot \\tanh(C_t)"
            }
          ]
        }
      },
      {
        "id": "seq2seq",
        "title": "The Seq2Seq Bottleneck",
        "body": "Sequence-to-Sequence (Sutskever et al., 2014) architectures translate an input sequence to an output sequence using two RNNs. The Encoder reads the input and compresses its entire meaning into a single, fixed-size 'context vector'. The Decoder then generates the output from this vector.\n\nThe Bottleneck: Forgetting. A single vector cannot hold the details of a 50-word sentence. Performance plummeted on long sequences because the encoder simply couldn't remember the beginning by the time it reached the end.",
        "anim": "seq2seq_bottle",
        "math": {
          "eqs": [
            {
              "l": "Complexity",
              "t": "\\text{Attention: } O(n^2 d) \\quad \\text{Recurrence: } O(n d)"
            }
          ]
        }
      },
      {
        "id": "bahdanau",
        "title": "The First Attention Mechanism (Bahdanau, 2014)",
        "body": "Seq2Seq models compressed entire input sentences into one fixed-size vector — a severe bottleneck for long inputs. Bahdanau et al. solved this with attention.\n\nAt each decoder step: (1) compute an alignment score e_{tj} between the current decoder state s_{t-1} and each encoder hidden state h_j using a small neural network; (2) normalize the scores with softmax to get attention weights α; (3) form a context vector c_t as the weighted sum of encoder states.\n\nThe decoder can now dynamically focus on whichever input positions are most relevant for generating each output token — rather than being forced to cram everything into a single vector. This was the conceptual seed from which Transformer self-attention grew.",
        "anim": "bahdanau",
        "math": {
          "eqs": [
            {
              "l": "Alignment score",
              "t": "e_{tj} = a(s_{t-1},\\, h_j)"
            },
            {
              "l": "Attention weights",
              "t": "\\alpha_{tj} = \\dfrac{\\exp(e_{tj})}{\\sum_k \\exp(e_{tk})}"
            },
            {
              "l": "Context vector",
              "t": "c_t = \\sum_j \\alpha_{tj}\\, h_j"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "transformer",
    "label": "03 — The Transformer",
    "title": "Attention Is All You Need (2017)",
    "color": "#00C9A7",
    "icon": "⚡",
    "subs": [
      {
        "id": "arch",
        "title": "Encoder-Decoder Architecture Overview",
        "body": "The original Transformer (Vaswani et al., 2017) is an encoder-decoder designed for machine translation. The encoder reads the entire input simultaneously and builds rich contextual representations. The decoder generates output one token at a time, attending to both its own outputs and the encoder's representations.\n\nBoth encoder and decoder are stacks of identical layers. Each layer contains: (1) a multi-head (self-)attention sub-layer, and (2) a position-wise feed-forward network sub-layer. Residual connections and layer normalization wrap each sub-layer.\n\nThe encoder uses bidirectional self-attention (each token can attend to all others). The decoder uses masked self-attention (each token can only attend to earlier generated tokens — causal masking) plus cross-attention to the encoder.",
        "anim": "enc_dec",
        "math": {
          "eqs": [
            {
              "l": "Encoder Output",
              "t": "\\mathbf{H} = \\text{Encoder}(\\mathbf{X}) \\in \\mathbb{R}^{n \\times d}"
            }
          ]
        }
      },
      {
        "id": "pos",
        "title": "Positional Encoding — Injecting Order",
        "body": "Self-attention processes all tokens simultaneously with no inherent notion of order. Without positional information, 'dog bites man' and 'man bites dog' look identical to the attention mechanism.\n\nSolution: add a fixed positional signal to each token embedding before entering the network. The sinusoidal encoding uses a geometric progression of frequencies — low frequencies encode coarse position; high frequencies encode fine-grained position.\n\nThe key mathematical property: for any fixed offset k, PE(pos+k) is a linear function of PE(pos). This means the model can learn to detect relative offsets between positions from absolute encodings alone, without ever being explicitly taught what 'distance 5 apart' looks like.",
        "anim": "posenc",
        "math": {
          "eqs": [
            {
              "l": "Even dims",
              "t": "PE(pos, 2i) = \\sin\\!\\left(\\dfrac{pos}{10000^{2i/d}}\\right)"
            },
            {
              "l": "Odd dims",
              "t": "PE(pos, 2i+1) = \\cos\\!\\left(\\dfrac{pos}{10000^{2i/d}}\\right)"
            }
          ]
        }
      },
      {
        "id": "attn",
        "title": "Scaled Dot-Product Self-Attention",
        "body": "Intuition: 'for this word's representation, which other words should influence it, and by how much?'\n\nStep 1 — Project: each token embedding X becomes three vectors via learned matrices. Query Q = XW_Q asks 'what am I looking for?' Key K = XW_K says 'what do I advertise?' Value V = XW_V says 'what will I contribute if attended to?'\n\nStep 2 — Score: compute raw relevance via dot products QK^T — an n×n matrix showing every pair's affinity.\n\nStep 3 — Scale: divide by √d_k. Why? For random vectors, the dot product variance scales with d_k. Large variances push softmax into saturated flat regions where gradients vanish. Dividing by √d_k keeps variance ≈ 1.\n\nStep 4 — Softmax: convert raw scores to a probability distribution over positions. The output is a convex combination of Value vectors — weighted average of what everyone offers, weighted by relevance.",
        "anim": "attn",
        "math": {
          "eqs": [
            {
              "l": "Q, K, V projections",
              "t": "Q=XW_Q,\\; K=XW_K,\\; V=XW_V"
            },
            {
              "l": "Scaled dot-product attention",
              "t": "\\text{Attn}(Q,K,V)=\\text{softmax}\\!\\left(\\dfrac{QK^\\top}{\\sqrt{d_k}}\\right)V"
            },
            {
              "l": "Softmax",
              "t": "\\text{softmax}(z_i)=\\dfrac{e^{z_i}}{\\sum_j e^{z_j}}"
            }
          ]
        }
      },
      {
        "id": "mha",
        "title": "Multi-Head Attention — Multiple Subspaces",
        "body": "A single attention computation captures one type of relationship at a time. Multi-head attention runs h independent attention operations in parallel, each in a lower-dimensional subspace of size d_k = d_model/h.\n\nWith d_model=512 and h=8, each head operates on 64 dimensions — the same total compute as single-head over the full 512 dimensions.\n\nThe outputs of all heads are concatenated and projected back to d_model via W_O. Empirically, different heads specialize: some track syntactic dependencies, some track long-range coreference, some focus on adjacent tokens, some encode semantic similarity. Multi-head attention gives the model multiple 'perspectives' simultaneously.",
        "anim": "mha",
        "math": {
          "eqs": [
            {
              "l": "Each head",
              "t": "\\text{head}_i = \\text{Attn}(QW_Q^i,\\, KW_K^i,\\, VW_V^i)"
            },
            {
              "l": "Multi-head",
              "t": "\\text{MHA}(Q,K,V) = \\text{Concat}(\\text{head}_1,\\ldots,\\text{head}_h)\\,W_O"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "def multi_head_attention(q, k, v, mask):\n    # q, k, v shape: (batch, heads, seq_len, head_dim)\n    scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(head_dim)\n    if mask is not None:\n        scores = scores + mask\n    probs = torch.softmax(scores, dim=-1)\n    return torch.matmul(probs, v)"
        }
      },
      {
        "id": "kvcache",
        "title": "KV-Cache: Inference Acceleration",
        "body": "During text generation, the model predicts one token at a time. To predict token $t$, the attention mechanism needs the Key and Value vectors of all $t-1$ previous tokens.\n\nRecomputing these past vectors every step is O(N^3) over the sequence length. Instead, models cache the $K$ and $V$ vectors in memory. For the new token, it only computes the new $Q, K, V$, appends the new $K, V$ to the cache, and attends to the cache. This reduces generation to O(N^2) time, but introduces a massive memory bottleneck (the KV-Cache memory footprint).",
        "anim": "kvcache",
        "code": {
          "lang": "python",
          "text": "def prefill(prompt, W):\n    kv_cache = []\n    for token in prompt:\n        k, v = W.k(token), W.v(token)\n        kv_cache.append((k, v))\n    return kv_cache\n\ndef decode(new_token, kv_cache, W):\n    k, v = W.k(new_token), W.v(new_token)\n    kv_cache.append((k, v))\n    # Attention over entire kv_cache\n    return compute_attention(W.q(new_token), kv_cache)"
        }
      },
      {
        "id": "causal_mask",
        "title": "The Causal Mask",
        "body": "In a decoder, tokens cannot look into the future during training, otherwise the task of 'predict the next word' becomes trivial cheating.\n\nA causal mask is an upper-triangular matrix of $-\\infty$ added to the $QK^\\top$ attention scores before the softmax. Since $e^{-\\infty} = 0$, the attention weights for future tokens become exactly zero. The model can only attend to itself and previous positions.",
        "anim": "causal_mask",
        "math": {
          "eqs": [
            {
              "l": "Masked Attention",
              "t": "\\text{softmax}\\left(\\frac{QK^\\top}{\\sqrt{d_k}} + M\\right)V"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "import torch\n\ndef get_causal_mask(seq_len):\n    # Lower triangular matrix\n    mask = torch.tril(torch.ones(seq_len, seq_len))\n    # Convert 0s to -inf for softmax\n    return mask.masked_fill(mask == 0, float('-inf'))"
        }
      },
      {
        "id": "ffn",
        "title": "Feed-Forward Network & Residual Connections",
        "body": "After attention mixes information across tokens, each token position is independently processed by a feed-forward network — a two-layer MLP applied identically to every position. The FFN expands to 4×d_model (the 'expansion ratio') and projects back.\n\nIf attention asks 'what information from where?', the FFN asks 'how should I transform this information?' Research suggests FFN layers act as key-value memories — the first matrix matches patterns, the second matrix reads out stored values.\n\nResidual connections: instead of just computing sublayer(x), compute x + sublayer(x). By the chain rule, ∂(x + f(x))/∂x = 1 + ∂f/∂x. The '1' term provides a direct gradient highway — gradients never vanish through the residual path, enabling networks of 100+ layers to train stably.",
        "anim": "ffn",
        "math": {
          "eqs": [
            {
              "l": "FFN (ReLU, original)",
              "t": "\\text{FFN}(x)=\\max(0,\\,xW_1+b_1)W_2+b_2"
            },
            {
              "l": "Residual connection",
              "t": "x \\leftarrow x + \\text{sublayer}(\\text{LN}(x))"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "class FFN(nn.Module):\n    def __init__(self, dim, hidden_dim):\n        super().__init__()\n        self.up = nn.Linear(dim, hidden_dim)\n        self.down = nn.Linear(hidden_dim, dim)\n        self.act = nn.GELU()\n\n    def forward(self, x):\n        return self.down(self.act(self.up(x)))"
        }
      },
      {
        "id": "loss",
        "title": "Cross-Entropy Loss & Training Objective",
        "body": "From information theory: entropy H(p) = −Σ p·log p measures irreducible uncertainty. Cross-entropy H(y,p) = −Σ y·log p is the expected code length when using model distribution p to encode samples from true distribution y. Minimizing cross-entropy drives p toward y.\n\nFor causal LMs (GPT-style): L = −Σ_t log P(x_t | x_{<t}) — sum the negative log-probability of each token given its preceding context. Teacher forcing: always feed ground-truth previous tokens during training (not the model's own predictions), which speeds and stabilizes learning.\n\nPerplexity = exp(L_CE) is the model's 'effective branching factor': how many equally likely choices it appears to be making at each step. Perplexity 10 means the model behaves as if choosing uniformly among 10 candidates — lower is better.",
        "anim": "xent",
        "math": {
          "eqs": [
            {
              "l": "Cross-entropy",
              "t": "L_{CE}=-\\sum_i y_i \\log(p_i)"
            },
            {
              "l": "Causal LM objective",
              "t": "L=-\\sum_t \\log P(x_t \\mid x_{<t})"
            },
            {
              "l": "Perplexity",
              "t": "\\text{PPL}=\\exp(L_{CE})"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "def cross_entropy(logits, targets):\n    # Standard language modeling objective\n    # Maximize log probability of correct next token\n    log_probs = F.log_softmax(logits, dim=-1)\n    return -log_probs.gather(dim=-1, index=targets.unsqueeze(-1)).mean()"
        }
      },
      {
        "id": "params",
        "title": "Parameter Count Analysis",
        "body": "For a Transformer with d-dimensional embeddings, h attention heads, and n layers:\n\n• Attention block: 4 weight matrices W_Q, W_K, W_V, W_O, each d×d → 4d² params per layer\n• FFN block (inner dim 4d): two matrices d→4d→d → 8d² params per layer\n• Total per layer: ~12d²\n• Embedding table: V×d (vocabulary size × hidden dim)\n\nValidation on GPT-3: d=12288, n=96, V≈50K → 96 × 12 × 12288² + 50000 × 12288 ≈ 174.5B + 0.6B ≈ 175B ✓\n\nKey implication: widening the model (increasing d) is quadratically expensive. Doubling d quadruples the parameter count. This is why MoE architectures — which scale total parameters without scaling active compute — became so attractive.",
        "anim": "params",
        "math": {
          "eqs": [
            {
              "l": "Per-layer params",
              "t": "\\approx 4d^2 + 8d^2 = 12d_{\\text{model}}^2"
            },
            {
              "l": "Total params",
              "t": "\\approx n \\times 12d_{\\text{model}}^2 + V \\times d_{\\text{model}}"
            }
          ]
        }
      },
      {
        "id": "regularizers",
        "title": "Regularization: Dropout & Label Smoothing",
        "body": "To prevent the millions of parameters from simply memorizing the training data (overfitting), the Transformer uses two key regularizers:\n\nDropout randomly zeroes out a percentage of neuron activations during training, forcing the network to build redundant, robust representations.\nLabel Smoothing prevents the model from becoming overly confident. Instead of aiming for 100% probability on the correct token and 0% on others, it aims for (e.g.) 90% on the correct token and distributes the remaining 10% uniformly across the rest of the vocabulary, preventing exploding gradients.",
        "math": {
          "eqs": [
            {
              "l": "Smoothed Target",
              "t": "y_k^{LS} = (1-\\alpha)y_k + \\alpha/K"
            }
          ]
        }
      },
      {
        "id": "beam",
        "title": "Beam Search Decoding",
        "body": "Greedy decoding only picks the immediate best next token. But what if a slightly suboptimal token now leads to a much better sequence later?\n\nBeam Search maintains the top-B most likely sequences (the 'beam width') at each step. It expands all B sequences, scores them, and keeps the new top-B. It is standard in tasks requiring strict correctness like translation or summarization, whereas stochastic sampling (Top-p) is preferred for open-ended creative generation."
      },
      {
        "id": "fwd_pass",
        "title": "Full Forward Pass Walkthrough",
        "body": "Putting it all together for one step of generation:\n1. Tokenize the input prompt into integer IDs.\n2. Lookup the embedding for each ID and add Positional Encoding.\n3. Pass through $N$ layers: compute Multi-Head Attention, add residual, apply LayerNorm, compute FFN, add residual, apply LayerNorm.\n4. Multiply the final hidden state by the unembedding matrix to get logits over the vocabulary.\n5. Apply Temperature and Softmax to get probabilities.\n6. Sample a token, append to prompt, and repeat."
      }
    ]
  },
  {
    "id": "clusterA",
    "label": "04 — Dense Transformers",
    "title": "Cluster A: Quadratic Attention O(n²)",
    "color": "#F7B731",
    "icon": "🧱",
    "subs": [
      {
        "id": "bert",
        "title": "Encoder-Only: BERT & Masked Language Modeling",
        "body": "BERT (Devlin et al., 2018) uses Masked Language Modeling (MLM): randomly replace ~15% of input tokens with a [MASK] placeholder, and train the model to predict the original tokens using bidirectional context — both left and right.\n\nBidirectionality is the key differentiator from GPT: each masked token's prediction can use information from any other position in the sequence. This makes BERT excellent for understanding tasks (classification, extraction, question answering) but unsuitable for autoregressive generation.\n\nA special [CLS] token prepended to every input accumulates a sentence-level representation via its final hidden state — useful for classification.\n\nKey descendants: RoBERTa dropped Next Sentence Prediction and added dynamic masking — matched BERT with better efficiency. ALBERT used cross-layer parameter sharing to reduce memory. DistilBERT used knowledge distillation to produce a 40%-smaller, 60%-faster model retaining 97% of BERT's performance.",
        "anim": "bert",
        "math": {
          "eqs": [
            {
              "l": "MLM loss",
              "t": "L_{\\text{MLM}}=-\\sum_{i\\in\\text{masked}}\\log P(x_i\\mid x_{\\text{context}})"
            }
          ]
        }
      },
      {
        "id": "gpt",
        "title": "Decoder-Only: GPT & Causal Language Modeling",
        "body": "GPT-1 (Radford et al., 2018) uses Causal Language Modeling (CLM): predict the next token given all previous tokens. A causal mask sets all future-position attention scores to −∞ before softmax, making those weights exactly 0.\n\nAutoregressive generation: feed a prompt, sample the next token from the output probability distribution, append it to the context, repeat. This loop generates sequences of arbitrary length.\n\nGPT-3 (175B, 2020) demonstrated in-context learning: present a few examples of a task in the prompt, and the model solves new instances without any weight updates. This is qualitatively different from fine-tuning — the 'learning' happens inside the forward pass, via attention computations over the context.\n\nDecoder-only became dominant for generation because: the CLM objective covers any text, scales cleanly with compute, and eliminates the need for paired input-output training data.",
        "anim": "gpt",
        "math": {
          "eqs": [
            {
              "l": "CLM objective",
              "t": "L=-\\sum_t\\log P(x_t\\mid x_{<t})"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "class TransformerBlock(nn.Module):\n    def __init__(self):\n        self.attn = MultiHeadAttention()\n        self.ffn = FeedForward()\n        self.ln1 = RMSNorm()\n        self.ln2 = RMSNorm()\n\n    def forward(self, x):\n        # Pre-normalization architecture\n        x = x + self.attn(self.ln1(x))\n        x = x + self.ffn(self.ln2(x))\n        return x"
        }
      },
      {
        "id": "t5",
        "title": "Encoder-Decoder: T5 & Span Corruption",
        "body": "T5 (Raffel et al., 2019) unified all NLP tasks as text-to-text: the model always takes a text string in and produces a text string out. 'Classify sentiment: I love this film' → 'positive'. 'Translate to French: Hello' → 'Bonjour'. Even regression becomes text: 'STS-B score: ...' → '3.8'.\n\nPre-training uses span corruption: randomly mask contiguous spans of tokens, have the decoder reconstruct only the masked spans. This preserves more context in the encoder than BERT-style per-token masking.\n\nCross-attention bridges encoder and decoder: at each decoder layer, the decoder representations are queries while the encoder's final representations are keys and values. This lets the decoder dynamically 'read' any part of the encoded input while generating output.\n\nBART (Lewis et al., 2019) is a denoising autoencoder — various corruptions (deletion, permutation, text infilling) applied to the input, decoder reconstructs the original. Especially strong for abstractive summarization.",
        "anim": "t5",
        "math": {
          "eqs": [
            {
              "l": "Cross-attention",
              "t": "\\text{Attn}(Q_{\\text{dec}},K_{\\text{enc}},V_{\\text{enc}})=\\text{softmax}\\!\\left(\\tfrac{Q_{\\text{dec}}K_{\\text{enc}}^\\top}{\\sqrt{d_k}}\\right)V_{\\text{enc}}"
            }
          ]
        }
      },
      {
        "id": "moe",
        "title": "Mixture of Experts (MoE)",
        "body": "Core intuition: instead of routing every token through every parameter, selectively activate a small subset of specialized 'expert' sub-networks. This decouples total parameters (knowledge capacity) from active compute (FLOPs per forward pass).\n\nEach MoE layer replaces the FFN with N expert FFNs. A gating network computes routing probabilities for each expert. Sparse MoE activates only the top-k experts per token — the others contribute nothing.\n\nLoad balancing is critical: without constraints, the router degenerates — it collapses onto a few favorite experts and ignores the rest. The auxiliary loss penalizes imbalance by minimizing Σ f_i · P_i across experts, where f_i is the fraction of tokens routed to expert i and P_i is the mean routing probability.\n\nDeepSeek-V3 (2024/25): 671B total parameters / 37B active per token. Uses 256 routed + 1 shared expert per layer, 8 activated per token. An auxiliary-loss-free load balancer uses per-expert bias terms instead of the standard loss term. Trained on 14.8T tokens in 2.788M H800 GPU-hours — a remarkably efficient frontier model.",
        "anim": "moe",
        "math": {
          "eqs": [
            {
              "l": "MoE output",
              "t": "y=\\sum_{i\\in\\text{top-k}} g_i(x)\\cdot E_i(x)"
            },
            {
              "l": "Gating",
              "t": "g(x)=\\text{softmax}(\\text{TopK}(xW_{\\text{gate}}))"
            },
            {
              "l": "Load-balance loss",
              "t": "L_{\\text{aux}}=\\alpha N\\sum_i f_i P_i"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "def sparse_moe(x, router, experts, top_k=2):\n    # router outputs logits for each expert\n    routing_logits = router(x)\n    routing_probs = torch.softmax(routing_logits, dim=-1)\n    \n    # Select top_k experts\n    top_probs, top_indices = torch.topk(routing_probs, top_k)\n    top_probs = top_probs / top_probs.sum(dim=-1, keepdim=True) # Normalize\n    \n    # Combine expert outputs\n    out = sum(prob * experts[idx](x) for prob, idx in zip(top_probs, top_indices))\n    return out"
        }
      },
      {
        "id": "gpt4",
        "title": "GPT-4 Architecture Notes (2023)",
        "body": "While OpenAI never published the exact architecture, widespread leaks and community consensus paint GPT-4 not as a single dense model, but a massive Mixture of Experts.\n\nEstimates suggest ~1.8 Trillion total parameters, split across 16 experts of ~111B parameters each. During inference, it routes each token to 2 experts, meaning active compute is 'only' ~280B parameters per token. This architectural leap allowed a massive increase in knowledge capacity without an unmanageable increase in inference latency."
      },
      {
        "id": "sft",
        "title": "Supervised Fine-Tuning (SFT)",
        "body": "Pre-training creates a 'document completer' that might respond to a question by asking more questions. SFT converts it into an assistant.\n\nSFT trains the model on tens of thousands of high-quality, human-written prompt-response pairs. The objective is exactly the same (next-token prediction cross-entropy), but the data distribution is entirely conversational. This teaches the model the *format* of interaction.",
        "code": {
          "lang": "python",
          "text": "def compute_sft_loss(logits, targets, ignore_index=-100):\n    # Only compute loss on target tokens, ignore prompt tokens\n    loss_fct = nn.CrossEntropyLoss(ignore_index=ignore_index)\n    # Shift logits and targets\n    shift_logits = logits[..., :-1, :].contiguous()\n    shift_labels = targets[..., 1:].contiguous()\n    return loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))"
        }
      },
      {
        "id": "rlhf",
        "title": "RLHF: Reinforcement Learning from Human Feedback",
        "body": "SFT is expensive (requires writing perfect answers) and limited by the human's skill. RLHF (Ouyang et al., 2022) scales alignment by having humans *grade* answers instead.\n\nStep 1: Train a Reward Model (RM) on human preference data (e.g., 'Response A is better than B'). The RM learns to score text quality.\nStep 2: Use PPO (Proximal Policy Optimization) to fine-tune the LLM to maximize the RM's score. A KL-divergence penalty ensures the LLM doesn't drift too far from the original SFT model (which would cause it to output 'reward-hacking' gibberish).",
        "math": {
          "eqs": [
            {
              "l": "RLHF Objective",
              "t": "\\max_{\\theta} \\mathbb{E}[R(x,y)] - \\beta \\mathbb{D}_{KL}(\\pi_\\theta || \\pi_{\\text{SFT}})"
            }
          ]
        }
      },
      {
        "id": "dpo",
        "title": "DPO: Direct Preference Optimization (2023)",
        "body": "RLHF is notoriously unstable because PPO involves multiple models acting simultaneously. DPO (Rafailov et al., 2023) eliminates the Reward Model and the RL loop entirely.\n\nMathematical insight: the RLHF objective can be solved exactly for the optimal policy. DPO reparameterizes the reward in terms of the policy itself. You can train the LLM directly on the human preference pairs using a simple binary cross-entropy loss. It is much more stable, requires less memory, and is now the industry standard (used in LLaMA 3).",
        "math": {
          "eqs": [
            {
              "l": "DPO Loss",
              "t": "L_{DPO} = -\\log \\sigma\\left(\\beta \\log \\frac{\\pi_\\theta(y_w)}{\\pi_{\\text{ref}}(y_w)} - \\beta \\log \\frac{\\pi_\\theta(y_l)}{\\pi_{\\text{ref}}(y_l)}\\right)"
            }
          ]
        }
      },
      {
        "id": "cai",
        "title": "Constitutional AI (Anthropic, 2022)",
        "body": "Relying on humans to label harmlessness is difficult because it exposes them to toxic content, and human values are subjective. Constitutional AI replaces human raters with an AI supervisor.\n\n1. Give the model a 'Constitution' (a list of principles like 'choose the response that is least racist').\n2. Have the model generate responses to toxic prompts, then ask it to critique and revise its own responses based on the constitution.\n3. Train the model on its own revised safe responses (RLAIF: RL from AI Feedback). Claude is built on this principle."
      },
      {
        "id": "distillation",
        "title": "Knowledge Distillation",
        "body": "How do you get a smart 8B model? Train it to mimic a 70B model.\n\nInstead of training the small model (student) on hard labels (one-hot distributions), train it to match the exact output probabilities (soft labels) of a large model (teacher). The soft labels contain 'dark knowledge' — for example, that a dog is 10% likely to be confused with a cat, but 0% likely to be confused with a car. This richer signal allows small models to punch far above their weight class.",
        "math": {
          "eqs": [
            {
              "l": "Distillation Loss",
              "t": "L = \\alpha L_{CE}(y, p_{\\text{student}}) + (1-\\alpha) T^2 \\mathbb{D}_{KL}(p_{\\text{teacher}}^{\\tau} || p_{\\text{student}}^{\\tau})"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "clusterB",
    "label": "05 — Linear & Recurrent",
    "title": "Cluster B: Sub-Quadratic O(n)",
    "color": "#A29BFE",
    "icon": "🌊",
    "subs": [
      {
        "id": "ssm",
        "title": "State Space Models: S4 → Mamba",
        "body": "SSMs treat sequence processing as a continuous-time dynamical system. An input signal u(t) drives a latent state x(t) through a linear ODE, and the output y(t) is read from the state.\n\nFor discrete sequences (tokens), this is discretized using a step size Δ to get a linear recurrence: x_k = Ā·x_{k-1} + B̄·u_k. Crucially, this recurrence can be computed two ways: as a recurrence (O(1) memory, efficient for inference) or as a 1D convolution via the convolution theorem (parallel, efficient for training).\n\nS4 (Gu et al., 2021): made SSMs work for long sequences by initializing the state matrix A using the HiPPO matrix — designed to optimally compress signal history using Legendre polynomials.\n\nMamba (Gu & Dao, 2023): adds selectivity — B, C, and the step size Δ become input-dependent functions of the current token u_k. The model dynamically decides what to remember and what to forget. Reports 5× throughput vs Transformers at matching quality.",
        "anim": "ssm",
        "math": {
          "eqs": [
            {
              "l": "Continuous SSM",
              "t": "x'(t)=Ax(t)+Bu(t),\\; y(t)=Cx(t)"
            },
            {
              "l": "Discrete recurrence",
              "t": "x_k=\\bar{A}x_{k-1}+\\bar{B}u_k,\\; y_k=Cx_k"
            },
            {
              "l": "Mamba selectivity",
              "t": "\\bar{B}_k=f_B(u_k),\\;\\bar{C}_k=f_C(u_k),\\;\\Delta_k=f_\\Delta(u_k)"
            }
          ]
        }
      },
      {
        "id": "linAttn",
        "title": "Linear Attention — Kernel Trick",
        "body": "The O(n²) cost of attention comes from materializing the n×n attention matrix. Linear attention approximates this using a feature map φ: softmax(QK^T) ≈ φ(Q)·φ(K)^T.\n\nThe key insight is matrix associativity: (φ(Q)·φ(K)^T)·V vs φ(Q)·(φ(K)^T·V). By computing φ(K)^T·V first — a small d×d matrix reusable for all queries — the total cost drops from O(n²·d) to O(n·d²).\n\nThe cost: softmax produces sharp, data-dependent attention weights that concentrate on a few highly relevant positions. Feature-map approximations produce softer weights — degrading quality on tasks requiring precise retrieval ('copy this exact token from position 47').",
        "anim": "linAttn",
        "math": {
          "eqs": [
            {
              "l": "Exact attention O(n²d)",
              "t": "\\text{Attn}(Q,K,V)=\\text{softmax}(QK^\\top/\\sqrt{d})\\,V"
            },
            {
              "l": "Linear attention O(nd²)",
              "t": "\\text{Attn}_{\\text{lin}}=\\dfrac{\\phi(Q)\\,(\\phi(K)^\\top V)}{\\phi(Q)\\cdot\\mathbf{1}^\\top\\phi(K)}"
            }
          ]
        }
      },
      {
        "id": "rwkv",
        "title": "RWKV — RNNs for the Transformer Era",
        "body": "RWKV (Peng et al., 2023) is an architecture that achieves: (1) Transformer-style parallel training, (2) RNN-style O(1) memory inference. It replaces attention with a time-mixing block based on the WKV operator.\n\nWKV is a weighted sum of past value vectors, where each past token's weight decays exponentially with distance at a learned rate w per channel. A bonus term u prevents the current token from being suppressed.\n\nThis can be computed as a prefix scan during training (parallel, log depth) or as a running recurrence during inference (O(1) memory). The same weights serve both modes — analogous to how SSMs support both convolution and recurrence.\n\nKey difference from SSMs: RWKV's time decay is a fixed learned scalar per channel, not an input-dependent matrix.",
        "anim": "rwkv",
        "math": {
          "eqs": [
            {
              "l": "WKV (time-mixing)",
              "t": "\\text{wkv}_t=\\frac{\\sum_{i<t} e^{-(t-i-1)w+k_i}v_i + e^{u+k_t}v_t}{\\sum_{i<t} e^{-(t-i-1)w+k_i} + e^{u+k_t}}"
            }
          ]
        }
      },
      {
        "id": "retnet",
        "title": "RetNet — Retention Networks",
        "body": "RetNet (Sun et al., 2023) introduces a retention mechanism with three equivalent computational forms enabling the 'impossible triangle': training parallelism, O(1) inference memory, and efficient chunk-wise processing.\n\nIn parallel form, Retention(Q,K,V) = (QK^T ⊙ D)V, where D is a causal decay mask: D_nm = γ^{n-m} for n≥m (else 0). The scalar γ ∈ (0,1) is the retention rate — controlling how quickly past tokens lose influence.\n\nPositional phases: Q and K vectors are multiplied by complex rotations e^{imθ} and e^{-inθ} respectively (similar to RoPE), so their inner product encodes relative position. Combined with exponential decay, retention is effectively linear attention + rotary phases + explicit exponential forgetting.\n\nThe recurrent form maintains a d×d state matrix that is updated with each new token — replacing the growing KV-cache with a fixed-size state.",
        "anim": "retnet",
        "math": {
          "eqs": [
            {
              "l": "Parallel retention",
              "t": "\\text{Ret}(Q,K,V)=(QK^\\top\\odot D)\\,V"
            },
            {
              "l": "Causal decay mask",
              "t": "D_{nm}=\\begin{cases}\\gamma^{n-m} & n\\ge m \\\\ 0 & \\text{else}\\end{cases}"
            }
          ]
        }
      },
      {
        "id": "hybrid",
        "title": "Hybrid Architectures (Jamba, Griffin)",
        "body": "While pure SSMs (like Mamba) solve the O(n²) memory bottleneck, they struggle with 'needle-in-a-haystack' retrieval tasks because they cannot perform exact lookups over long contexts—everything is compressed into a fixed-size state.\n\nHybrid architectures combine the best of both worlds. **Jamba (AI21, 2024)** interleaved Transformer layers with Mamba layers (e.g., a ratio of 1:7) and added MoE (Mixture of Experts). The few Attention layers maintain precise retrieval across the context window, while the Mamba layers handle local processing and sequence mixing with O(1) memory footprint.\n\nSimilarly, **Griffin (DeepMind, 2024)** combines local attention (windowed) with linear RNNs. By restricting attention to a local window, it bounds the KV-cache size, while the RNN aggregates global context.",
        "math": {
          "eqs": [
            {
              "l": "Exposure Fraction",
              "t": "\\text{Ratio} = \\frac{1 \\text{ Attn}}{7 \\text{ Mamba}}, \\text{ Cost} \\propto \\frac{1}{8} O(n^2)"
            }
          ]
        }
      },
      {
        "id": "sparse",
        "title": "Sparse & Windowed Attention",
        "body": "Instead of abandoning attention, another path is to compute it sparsely. Full attention computes a score for every token against every other token. Sparse attention restricts this.\n\n**Local/Windowed Attention (e.g., Longformer, Mistral):** Tokens only attend to a sliding window of recent tokens (e.g., the last 4096 tokens). This caps memory at O(n·w) instead of O(n²).\n**Strided/Dilated Attention:** Tokens attend to distant tokens at regular intervals (e.g., every 8th token) to capture long-range structure without full computation.\n**Block-Sparse Attention (e.g., BigBird):** A mix of local windows, random distant tokens, and a few 'global' tokens (like a [CLS] token) that attend to everything. BigBird proved this is Turing complete."
      }
    ]
  },
  {
    "id": "alt",
    "label": "06 — Alternative Architectures",
    "title": "Beyond the Transformer Stack",
    "color": "#6C63FF",
    "icon": "🛸",
    "subs": [
      {
        "id": "kan",
        "title": "KAN (Kolmogorov-Arnold Networks)",
        "body": "KANs (Liu et al., 2024) challenge the fundamental structure of MLPs. In a standard MLP, there are fixed activation functions (like ReLU or SiLU) on nodes, and learnable linear weights on the edges.\n\nKANs invert this based on the Kolmogorov-Arnold representation theorem. In a KAN, the nodes simply sum their inputs, and the *edges* contain learnable non-linear functions (parameterized as 1D B-splines).\n\nBenefits: KANs are highly interpretable (you can inspect the learned 1D curves) and avoid catastrophic forgetting in continual learning. They can achieve matching accuracy to MLPs with far fewer parameters, though their training wall-clock time is significantly slower due to the lack of hardware-optimized spline operations.",
        "math": {
          "eqs": [
            {
              "l": "Standard MLP",
              "t": "y = \\sigma(Wx)"
            },
            {
              "l": "KAN Edge",
              "t": "\\phi(x) = w\\left(b(x) + \\sum c_i B_i(x)\\right)"
            }
          ]
        }
      },
      {
        "id": "liquid",
        "title": "Liquid Neural Networks",
        "body": "Liquid Neural Networks (Hasani et al., 2021) are continuous-time recurrent networks inspired by the nervous system of C. elegans.\n\nUnlike traditional RNNs where the 'time constant' (how fast the state updates) is fixed, Liquid networks feature *input-dependent time constants*. Their internal equations literally adapt their structure to the incoming data stream, making them highly resilient to noise and out-of-distribution shifts (like changing the frame rate of a video or encountering turbulence in a drone flight).\n\nWhile highly parameter-efficient (solving autonomous driving tasks with ~20,000 parameters), scaling them to LLM sizes remains an open research problem due to the complexity of solving their differential equations during training."
      },
      {
        "id": "testcompute",
        "title": "Test-Time Compute (o1 / o3)",
        "body": "For years, scaling laws focused on *training compute* (pre-training flops). In late 2024, models like OpenAI's o1 introduced scaling laws for *inference compute* (test-time compute).\n\nInstead of generating an answer instantly, the model uses RL-trained latent reasoning processes to 'think'. It generates multiple possible reasoning chains, critiques its own steps, backtracks on errors, and explores a search tree of solutions before outputting the final answer.\n\nThis mirrors AlphaGo's Monte Carlo Tree Search (MCTS). The longer the model is allowed to 'think' at inference time, the higher its accuracy on complex math and coding tasks. This shifts the compute bottleneck from massive pre-training runs to dynamic allocation at inference."
      }
    ]
  },
  {
    "id": "tokenizers",
    "label": "07 — Tokenizers",
    "title": "Tokenizer Evolution",
    "color": "#00B894",
    "icon": "✂️",
    "subs": [
      {
        "id": "whytok",
        "title": "Why Tokens? The Vocabulary Trade-off",
        "body": "A token is the atomic discrete unit the model consumes — its input is always a sequence of integer token IDs, never raw text.\n\nThe design choice of tokenization strategy determines vocabulary size and sequence length, and the trade-off between them is fundamental:\n\n• Characters only: vocabulary of ~100 symbols, sequences 4–6× longer, long-range dependencies harder.\n• Words only: short sequences but an open-ended vocabulary where every new typo or domain term becomes 'unknown'.\n• Subwords: the Goldilocks compromise — common words are single tokens, rare words split into recognizable morphological pieces. Vocabulary is fixed and finite; sequences are manageable.\n\nThe key tension: larger vocabulary → shorter sequences (cheaper computation) but sparser statistics per token (harder to learn embeddings). Smaller vocabulary → richer per-token statistics but longer sequences and more O(n²) attention cost.",
        "anim": "toktradeoff",
        "math": {
          "eqs": [
            {
              "l": "Vocabulary Mapping",
              "t": "V: \\text{token} \\to \\mathbb{Z}, \\, |V| \\in [32K, 200K]"
            }
          ]
        }
      },
      {
        "id": "bpe",
        "title": "BPE — Byte Pair Encoding (Sennrich, 2016)",
        "body": "BPE was originally a compression algorithm. Adapted for NLP: start with individual characters as the vocabulary. Iteratively find the most frequent adjacent pair of tokens in the training corpus, merge them into one new token, and repeat until reaching the target vocabulary size.\n\nGPT-2 extended BPE to byte-level: treat raw UTF-8 bytes (0–255) as base units. Because every string is representable as bytes, there are literally zero unknown tokens — any input, language, code, or emoji is guaranteed to be encodable.\n\nTiktoken (OpenAI): cl100k_base (100,277 tokens) used by GPT-3.5/4; o200k_base (200K+ tokens) for newer models.\n\nGlitch tokens (2023 discovery, 'SolidGoldMagikarp'): GPT-2's tokenizer assigned dedicated embeddings to obscure Reddit usernames that appeared rarely or never in the model's training data. Those embeddings remained near-random. The model could not reproduce them and instead produced erratic outputs. Largely fixed in cl100k_base.",
        "anim": "bpe",
        "math": {
          "eqs": [
            {
              "l": "BPE merge rule",
              "t": "(a,b)^*=\\arg\\max_{(a,b)}\\text{count}(a,b)"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "def byte_pair_encoding(vocab, num_merges):\n    for _ in range(num_merges):\n        pairs = get_stats(vocab)\n        if not pairs:\n            break\n        # Find most frequent pair\n        best = max(pairs, key=pairs.get)\n        # Merge pair in vocabulary\n        vocab = merge_vocab(best, vocab)\n    return vocab"
        }
      },
      {
        "id": "wordpiece",
        "title": "WordPiece & Unigram LM Tokenizer",
        "body": "WordPiece (Wu et al., 2016): similar to BPE but selects merges by likelihood gain rather than raw frequency. Score(a,b) = count(ab)/(count(a)·count(b)) — favoring pairs whose combination is much more common than chance would predict. Continuation subwords carry a '##' prefix. Used by BERT, RoBERTa, ELECTRA.\n\nUnigram LM (Kudo, 2018): the inverse approach — start with a large candidate vocabulary and prune it. Each sentence's probability is the product of its tokens' unigram probabilities. Training: EM loop — estimate probabilities, compute each token's marginal contribution, prune the bottom-x% tokens, repeat until reaching the target vocabulary size.\n\nBecause multiple valid segmentations of a sentence exist under Unigram, the tokenizer is probabilistic — during training, you can sample different segmentations, which acts as regularization. Used by T5, ALBERT, mT5.",
        "anim": "wordpiece",
        "math": {
          "eqs": [
            {
              "l": "WordPiece merge score",
              "t": "\\text{score}(a,b)=\\dfrac{\\text{count}(ab)}{\\text{count}(a)\\cdot\\text{count}(b)}"
            },
            {
              "l": "Unigram sentence prob",
              "t": "P(x)=\\prod_i p(x_i)"
            }
          ]
        }
      },
      {
        "id": "sp",
        "title": "SentencePiece & Byte-Level Tokenization",
        "body": "SentencePiece (Kudo & Richardson, 2018) is a framework, not an algorithm — it wraps BPE or Unigram LM with a crucial difference: it treats the entire raw text (including spaces and newlines) as a sequence of Unicode characters, marking word boundaries with the visible character ▁. No language-specific word-splitting rules are ever needed. Handles Chinese, Japanese, Arabic, Thai natively. Used by T5, LLaMA, Gemma, mT5.\n\nByT5 (Xue et al., 2021): process directly on UTF-8 bytes. Vocabulary = exactly 256. Zero unknown tokens guaranteed. Any script, any code, any binary-adjacent content is representable. Trade-off: sequences are 3–4× longer for typical text, greatly increasing compute requirements.\n\nMultilingual disparity: English-centric BPE vocabularies assign 2–4 tokens to a single Chinese or Arabic character, meaning non-English users pay 2–4× more in API costs and have proportionally less usable context window for the same text.",
        "anim": "sp",
        "math": {
          "eqs": [
            {
              "l": "Byte Entropy",
              "t": "H(byte) = -\\sum_{b=0}^{255} p(b)\\log p(b)"
            }
          ]
        }
      },
      {
        "id": "regex",
        "title": "Tiktoken & Regex Filtering",
        "body": "Modern tokenizers like OpenAI's tiktoken use complex regex patterns *before* applying BPE merges. This prevents the tokenizer from merging tokens across natural boundaries (like punctuation, spaces, or numbers).\n\nFor example, it forces numbers to be split into up to 3 digits (e.g., '1000' -> '100', '0') to ensure more consistent mathematical representation, although it's not perfect."
      },
      {
        "id": "numbers",
        "title": "The Numbers Problem",
        "body": "LLMs historically struggle with arithmetic. A major reason is tokenization. If ' 1' is token A, '1' is token B, and '123' is token C, the model has to learn addition from scratch for every possible token representation of a number.\n\nLlama 3 and recent models force tokenizers to split all numbers into individual digits. By standardizing the input representation (every number is a sequence of base-10 digits), the transformer can finally learn the underlying algorithmic rules of addition and multiplication more reliably."
      }
    ]
  },
  {
    "id": "training",
    "label": "08 — Training & Hardware",
    "title": "Activations, Optimizers & Systems",
    "color": "#FDCB6E",
    "icon": "🧪",
    "subs": [
      {
        "id": "act",
        "title": "Activation Functions: ReLU → GELU → SwiGLU",
        "body": "Activation functions introduce nonlinearity — without them, any stack of linear layers collapses to a single linear transformation.\n\nReLU f(x) = max(0,x): simple, fast, but the 'dying ReLU' problem — neurons whose inputs are always negative output 0 with exactly zero gradient, permanently stopping learning.\n\nGELU (Hendrycks & Gimpel, 2016): f(x) = x·Φ(x) where Φ is the standard normal CDF. This smoothly gates each input by how likely it is to be positive. Unlike ReLU's hard cutoff, GELU gives small non-zero gradients for negative inputs. Approximated by a tanh formula for efficient computation. Used by BERT, GPT-2/3.\n\nSwiGLU (Shazeer, 2020): a gated architecture. FFN(x) = Swish(xW₁)⊙(xW₂), where Swish(x) = x·σ(x). The second branch acts as an input-dependent gate. Because this introduces a third projection matrix, the inner dimension is reduced to (2/3)×4d_model to keep total FLOPs constant. Empirically the best activation for Transformers. Now default in LLaMA, PaLM, Mistral, Qwen, DeepSeek.",
        "anim": "acts",
        "math": {
          "eqs": [
            {
              "l": "ReLU",
              "t": "\\text{ReLU}(x)=\\max(0,x)"
            },
            {
              "l": "GELU (approximation)",
              "t": "\\text{GELU}(x)\\approx 0.5x\\left(1+\\tanh\\!\\left(\\sqrt{\\tfrac{2}{\\pi}}(x+0.044715x^3)\\right)\\right)"
            },
            {
              "l": "SwiGLU",
              "t": "\\text{SwiGLU}(x,W_1,W_2)=\\underbrace{xW_1\\cdot\\sigma(xW_1)}_{\\text{Swish}}\\odot (xW_2)"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "import torch\nimport torch.nn.functional as F\n\ndef swiglu(x, W, V):\n    # x: (batch, dim)\n    # W, V: linear projections\n    gate = F.silu(x @ W)  # SiLU is Swish(x)\n    val = x @ V\n    return gate * val"
        }
      },
      {
        "id": "norm",
        "title": "Normalization: LayerNorm vs. RMSNorm",
        "body": "Without normalization, the distribution of each layer's inputs shifts as earlier layer weights update — 'internal covariate shift' — causing training instability and requiring very low learning rates.\n\nLayerNorm (Ba et al., 2016): for each example independently, normalize across the feature dimension using mean and variance, then apply learnable scale γ and shift β. Different from BatchNorm (normalizes across the batch), which is inappropriate for variable-length sequences.\n\nPre-Norm vs Post-Norm: the original Transformer applied LN after the residual: x = LN(x + sublayer(x)). Modern models (GPT-2 onward) apply LN before: x = x + sublayer(LN(x)). Pre-Norm preserves a clean residual stream, enabling much deeper and more stable networks.\n\nRMSNorm (Zhang & Sennrich, 2019): drops the mean-centering step — normalizes only by the root mean square of activations. ~15% cheaper to compute, empirically matches LayerNorm quality. Now standard in LLaMA, Mistral, Gemma, Qwen, DeepSeek.",
        "anim": "norm",
        "math": {
          "eqs": [
            {
              "l": "LayerNorm",
              "t": "\\text{LN}(x)=\\gamma\\cdot\\dfrac{x-\\mu}{\\sqrt{\\sigma^2+\\varepsilon}}+\\beta"
            },
            {
              "l": "RMSNorm",
              "t": "\\text{RMSNorm}(x)=\\dfrac{x}{\\text{RMS}(x)}\\cdot\\gamma,\\quad\\text{RMS}(x)=\\sqrt{\\tfrac{1}{d}\\sum_i x_i^2}"
            },
            {
              "l": "Pre-Norm (modern)",
              "t": "x \\leftarrow x + \\text{sublayer}(\\text{RMSNorm}(x))"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "import torch\n\nclass RMSNorm(torch.nn.Module):\n    def __init__(self, dim, eps=1e-6):\n        super().__init__()\n        self.eps = eps\n        self.weight = torch.nn.Parameter(torch.ones(dim))\n\n    def forward(self, x):\n        # Root Mean Square\n        rms = torch.sqrt(torch.mean(x**2, dim=-1, keepdim=True) + self.eps)\n        return (x / rms) * self.weight"
        }
      },
      {
        "id": "rope",
        "title": "RoPE — Rotary Position Embedding",
        "body": "RoPE (Su et al., 2021) is the dominant positional encoding in modern LLMs. Core idea: encode position by rotating Q and K vectors in 2D subspaces.\n\nFor each dimension pair (2i, 2i+1), apply a 2D rotation matrix by angle m·θᵢ, where m is the token position and θᵢ = 10000^{−2i/d} is a frequency (geometric progression, like sinusoidal PE).\n\nThe crucial mathematical property: the dot product q_m·k_n after applying their rotations equals f(m−n) — it depends only on the relative offset, not the absolute positions. Relative position emerges naturally from absolute rotations.\n\nAdvantages: parameter-free (no learned table); works with linear attention; extrapolates more gracefully than learned absolute embeddings; compatible with standard self-attention kernels.\n\nUsed by: LLaMA (all versions), Mistral, Qwen, Falcon, Gemma, DeepSeek.\n\nYaRN (Peng et al., 2023): extends RoPE beyond training context by interpolating rotary frequencies — ~2.5× fewer fine-tuning steps than position interpolation (PI).",
        "anim": "rope",
        "math": {
          "eqs": [
            {
              "l": "2D rotation at position m",
              "t": "\\begin{bmatrix}q_{2i}'\\\\q_{2i+1}'\\end{bmatrix}=\\begin{bmatrix}\\cos m\\theta_i & -\\sin m\\theta_i\\\\\\sin m\\theta_i & \\cos m\\theta_i\\end{bmatrix}\\begin{bmatrix}q_{2i}\\\\q_{2i+1}\\end{bmatrix}"
            },
            {
              "l": "Frequency schedule",
              "t": "\\theta_i=10000^{-2i/d}"
            },
            {
              "l": "Relative distance property",
              "t": "q_m^\\top k_n = f(m-n)\\quad\\text{(only depends on relative offset)}"
            }
          ]
        },
        "code": {
          "lang": "python",
          "text": "def apply_rope(q, k, positions):\n    # Rotate adjacent pairs of dimensions\n    q_rotated = q * cos(positions) + rotate_half(q) * sin(positions)\n    k_rotated = k * cos(positions) + rotate_half(k) * sin(positions)\n    return q_rotated, k_rotated"
        }
      },
      {
        "id": "disttrain",
        "title": "Distributed Training Dimensions",
        "body": "Training frontier models requires splitting the workload across thousands of GPUs.\n\n• **Data Parallelism (DP/FSDP):** Copy the model weights to every GPU, split the data. FSDP shards the optimizer states and weights to save memory.\n• **Tensor Parallelism (TP):** Split individual matrix multiplications across GPUs (e.g., Q, K, V projections). Requires extremely high-bandwidth interconnects (NVLink) because of all-reduce operations.\n• **Pipeline Parallelism (PP):** Split the model by layers across GPUs (GPU 1 computes layers 1-4, then sends activations to GPU 2 for layers 5-8).\n• **Expert Parallelism (EP):** For MoE models, different GPUs host different experts. Tokens are routed across the network to the correct GPU."
      },
      {
        "id": "optim",
        "title": "Modern Optimizers (AdamW to Muon)",
        "body": "AdamW has been the default optimizer since 2017, combining adaptive learning rates (using momentum and variance) with decoupled weight decay.\n\nHowever, AdamW scales memory poorly because it keeps two state variables (moment 1 and 2) per parameter. \n\nNewer optimizers are challenging this:\n• **Sophia (2023):** A second-order optimizer using a light-weight diagonal Hessian estimate. Updates clip gradients dynamically. Claims 2x faster convergence than Adam.\n• **Muon (2024):** Used in DeepSeek training. It applies orthogonalization (Newton-Schulz iteration) to the gradients of weight matrices, effectively preconditiong them without storing large momentum tensors. Extremely memory efficient."
      },
      {
        "id": "flashhw",
        "title": "FlashAttention Internals",
        "body": "While conceptually solving the memory bottleneck, FlashAttention is really a masterclass in hardware-aware programming. GPUs have a massive but slow memory pool (HBM) and a tiny but incredibly fast memory pool (SRAM).\n\nStandard attention writes intermediate matrices (like QK^T) to HBM, then reads them back to apply Softmax. This IO bottleneck dominates the runtime.\n\nFlashAttention aggressively tiles the Q, K, and V blocks to fit exactly into SRAM. It computes the attention incrementally (online softmax) and only writes the final output back to HBM. FlashAttention-3 goes further, exploiting the Hopper architecture's asynchronous DMA and Tensor Cores to overlap data movement with math.",
        "anim": "roofline"
      }
    ]
  },
  {
    "id": "infer",
    "label": "09 — Inference & Deployment",
    "title": "Serving at Scale",
    "color": "#0984E3",
    "icon": "🚀",
    "subs": [
      {
        "id": "quant",
        "title": "Quantization (PTQ & GGUF)",
        "body": "FP16 requires 2 bytes per parameter (a 70B model needs 140GB of VRAM just to load). Quantization compresses this to 8-bit, 4-bit, or even lower.\n\n• **PTQ (Post-Training Quantization):** Reduces precision after training. Methods like GPTQ and AWQ are data-aware—they look at a small calibration dataset to protect the most important 'outlier' weights from being rounded into oblivion.\n• **GGUF:** A popular file format that allows running heavily quantized models (e.g., Q4_K_M) efficiently on consumer hardware (MacBooks and CPU/RAM)."
      },
      {
        "id": "specdecode",
        "title": "Speculative Decoding",
        "body": "Inference is memory-bandwidth bound, not compute bound. When generating a token, the GPU does a massive matrix multiplication but only processes batch-size 1. Most of the compute capacity sits idle.\n\nSpeculative Decoding fixes this by pairing a small, fast 'draft' model with the massive 'target' model.\n1. The draft model rapidly generates 4-5 tokens.\n2. The target model processes all 4-5 tokens in a single parallel forward pass to verify them.\n3. Because LLMs run faster in parallel (prefill) than sequentially (decode), this provides a 2-3x speedup with absolutely zero loss in quality—it is mathematically identical to running the target model alone.",
        "anim": "specdecode"
      },
      {
        "id": "vllm",
        "title": "Continuous Batching & PagedAttention",
        "body": "Serving thousands of users requires batching their requests. But requests arrive at random times and have different lengths.\n\n• **Continuous Batching:** Instead of waiting for a batch to finish, the engine ejects completed requests and inserts new ones at the very next token iteration.\n• **PagedAttention (vLLM, 2023):** Inspired by OS virtual memory. Previously, KV-cache was allocated in massive contiguous blocks, leading to terrible fragmentation (up to 60% memory waste). PagedAttention splits the KV-cache into small blocks (e.g., 16 tokens) that can be stored non-contiguously in VRAM. This tripled serving throughput for the industry."
      }
    ]
  },
  {
    "id": "gaps",
    "label": "10 — Critical Gaps & Scaling",
    "title": "What Remains Unsolved",
    "color": "#E17055",
    "icon": "⚠️",
    "subs": [
      {
        "id": "o2",
        "title": "The O(n²) Efficiency Bottleneck",
        "body": "Attention computes a relevance score between every pair of tokens: an n×n matrix for a sequence of n tokens. Both compute (O(n²) multiply-adds) and memory (O(n²) matrix storage) scale quadratically.\n\nThe KV-cache problem: during autoregressive inference, the keys and values for every past token are cached to avoid recomputation. For a 70B model at 128K context in fp16, this cache can exceed 128GB — more than fits on most GPU clusters. The cache is the dominant memory cost at long contexts.\n\nFlashAttention (Dao et al., 2022): IO-aware algorithm that never materializes the full N×N attention matrix in slow high-bandwidth memory (HBM). Instead, it tiles computation into blocks fitting in fast on-chip SRAM, computing attention with an online-softmax algorithm. Cuts memory traffic 10–20× and gives ~7.6× wall-clock speedup on attention. Critically: it does NOT change the O(n²) complexity class. FlashAttention-2 and -3 extend these gains to newer GPU architectures.",
        "anim": "o2",
        "math": {
          "eqs": [
            {
              "l": "Attention matrix memory",
              "t": "\\text{Mem}=O(n^2) \\text{ bytes for length }n"
            },
            {
              "l": "KV-cache size",
              "t": "2\\times L\\times H\\times d_k\\times T\\times B\\times\\text{sizeof}(\\text{dtype})"
            }
          ]
        }
      },
      {
        "id": "ruler",
        "title": "RULER: Nominal vs. Functional Context",
        "body": "The RULER benchmark (Hsieh et al., 2024) exposed the gap between a model's claimed context window and its functional context — the length over which it can actually reason reliably.\n\nRULER goes beyond simple Needle-in-a-Haystack (NIAH) — where a key fact is planted in a long document — to 13 task types: multi-hop tracing (follow chains of references), aggregation (count all occurrences), variable tracking, and selective filtering, all tested from 4K to 128K tokens.\n\nHeadline finding: of 17 long-context models benchmarked, only half could effectively handle 32K tokens despite all advertising 32K+. GPT-4 degraded least but still dropped 15.4 points from 4K to 128K. Most models show a sharp performance cliff well before their advertised limit.\n\nMRCR v2 (Multi-Range Context Retrieval): tests finding and integrating multiple non-adjacent pieces of evidence — significantly harder than single-needle NIAH and a better proxy for real-world usage.",
        "anim": "ruler",
        "math": {
          "eqs": [
            {
              "l": "Functional Context",
              "t": "C_{eff} = \\max \\{L \\mid \\text{Accuracy}(L) > \\tau\\}"
            }
          ]
        }
      },
      {
        "id": "ssa",
        "title": "SSA/SubQ — The 2026 Efficiency Case Study",
        "body": "SubQ (Subquadratic Sparse Attention, 2026) represents the newest architectural bet: content-dependent sparse attention that selects which positions matter for each query, computing exact (not approximated) attention only over those positions. This aims to preserve the retrieval precision of full attention while achieving sub-quadratic scaling.\n\nVendor-published figures (May 2026, from an Appen white paper):\n• 56.2× prefill speedup at 1M tokens vs FlashAttention-2 (21,410ms → 380.96ms on B200)\n• 62.8× reduction in attention FLOPs at 1M tokens\n• RULER@128K: 95.6%   •   MRCR v2: 86.2%   •   SWE-Bench Verified: 81.8%\n\nArchitectural position: distinct from prior approaches — unlike fixed-pattern sparsity (Longformer/BigBird) its routing is content-driven; unlike SSMs it preserves exact arbitrary-position retrieval; unlike hybrids (Jamba) it has no load-bearing dense attention layers.\n\n⚠ These are vendor-published figures pending broad independent reproduction as of mid-2026.",
        "anim": "ssa",
        "math": {
          "eqs": [
            {
              "l": "Reported speedup @ 1M tokens",
              "t": "\\frac{21{,}410\\text{ms (FA2)}}{380.96\\text{ms (SSA)}}\\approx 56.2\\times"
            }
          ]
        }
      },
      {
        "id": "datawall",
        "title": "The Data Wall",
        "body": "Epoch AI's analysis ('Will We Run Out of Data?', Villalobos et al.) estimates the effective stock of quality, repetition-adjusted human-generated public text at approximately 300 trillion tokens, with a 90% CI spanning 100T–1000T.\n\nTheir projection: this stock will be fully utilized between 2026 and 2032, with a median around 2028 — possibly sooner if training continues at the 'overtrained' rate. LLaMA 3 was estimated to be trained ~10× the Chinchilla-optimal number of passes on some datasets.\n\nMitigations under active research:\n• Synthetic data: generate training data using existing models — especially valuable for math, code, and reasoning where correctness is verifiable\n• Multimodal data: video, images, and audio are largely untapped\n• Data efficiency: architectural improvements that learn better from fewer tokens\n• Curriculum learning: better ordering and weighting of training examples",
        "anim": "datawall",
        "math": {
          "eqs": [
            {
              "l": "Utilization Curve",
              "t": "D_{avail}(t) = D_0 \\cdot e^{k \\cdot (t - t_0)}"
            }
          ]
        }
      },
      {
        "id": "interp",
        "title": "The Interpretability Deficit & Alignment Gap",
        "body": "We cannot reliably explain what individual attention heads, neurons, or layers 'do' in a trained model. We can detect that a layer encodes syntactic structure using probing classifiers, but we cannot trace a specific output to specific mechanisms with confidence.\n\nCurrent research directions:\n• Sparse Autoencoders (SAEs): decompose residual-stream activations into monosemantic 'features' — units that activate for specific interpretable concepts (e.g., 'this token is part of a DNA sequence'). More interpretable than raw neurons, which tend to be polysemantic.\n• Circuit analysis: identify the minimal set of attention heads and MLP neurons implementing a specific capability.\n• Probing: train linear classifiers on hidden states to detect what information is encoded at each layer.\n\nThe alignment gap: RLHF and DPO successfully align surface behavior — models follow instructions, refuse harmful requests, sound more helpful. But they do not reliably fix factual accuracy. An RLHF-trained model can be confidently and fluently wrong. The mechanisms for truthfulness and for instruction-following are largely orthogonal.",
        "anim": "sae",
        "math": {
          "eqs": [
            {
              "l": "Probing Classifier",
              "t": "\\min_W \\sum_i L(W h_i, y_i) + \\lambda ||W||^2"
            }
          ]
        }
      },
      {
        "id": "haltax",
        "title": "Hallucination Taxonomy",
        "body": "Hallucinations are not bugs in the code; they are a fundamental consequence of how next-token prediction works. They fall into distinct categories:\n\n• **Closed-Domain (Factual Contradiction):** The model contradicts information directly provided in the prompt.\n• **Open-Domain (World Knowledge):** The model confidently states something factually incorrect about the world.\n• **Logical (Reasoning Flaw):** The model makes a mathematical or deductive error.\n\nThe root cause: LLMs do not have a grounded world model or a 'database of truth'. They have a statistical map of language. When they don't 'know' an answer, they don't naturally output 'I don't know' unless heavily RLHF-trained to do so. Instead, they sample the most plausible-sounding tokens, which seamlessly constructs a lie."
      },
      {
        "id": "goodhart",
        "title": "Benchmark Saturation & Goodhart's Law",
        "body": "'When a measure becomes a target, it ceases to be a good measure.'\n\nClassic benchmarks like MMLU (Massive Multitask Language Understanding) are increasingly saturated (models scoring 90%+). However, this often doesn't correlate with real-world usefulness.\n\nTwo problems:\n1. **Data Contamination:** Benchmark questions frequently leak into the massive pre-training sets. The model isn't reasoning; it's retrieving memorized answers.\n2. **Over-optimization:** RLHF and specialized fine-tuning heavily optimize for benchmark formats (like multiple choice) at the expense of general capabilities (the 'alignment tax')."
      }
    ]
  },
  {
    "id": "scaling",
    "label": "11 — Scaling Laws",
    "title": "The Economics of Scale",
    "color": "#74B9FF",
    "icon": "📈",
    "subs": [
      {
        "id": "kaplan",
        "title": "Kaplan Scaling Laws (2020)",
        "body": "Kaplan et al. (OpenAI, 2020) showed that the test loss of language models follows smooth power laws in model size N, dataset size D, and compute budget C — independently and over many orders of magnitude.\n\nThe key insight: these power laws are stable and predictable, allowing reliable extrapolation. You can train many small models, fit the power law, and forecast how a model 100× larger will perform before spending the compute to train it. This predictability justified massive long-horizon investment.\n\nImplication at the time: maximize model size given compute (data was considered secondary). This logic led to GPT-3 (175B parameters trained on ~300B tokens) and other large, relatively undertrained models.",
        "anim": "scaling",
        "math": {
          "eqs": [
            {
              "l": "Loss vs. model size",
              "t": "L(N)\\propto N^{-\\alpha_N},\\; \\alpha_N\\approx 0.076"
            },
            {
              "l": "Loss vs. data",
              "t": "L(D)\\propto D^{-\\alpha_D},\\; \\alpha_D\\approx 0.095"
            },
            {
              "l": "Loss vs. compute",
              "t": "L(C)\\propto C^{-\\alpha_C},\\; \\alpha_C\\approx 0.050"
            }
          ]
        }
      },
      {
        "id": "chinchilla",
        "title": "Chinchilla Scaling Laws (2022) — The Correction",
        "body": "Hoffmann et al. (DeepMind, 2022) ran a rigorous compute-optimal study: train 400+ models from 70M to 16B parameters on 5B to 500B tokens under fixed compute budgets. Question: given a budget of C FLOPs, what is the optimal model size N* and dataset size D*?\n\nResult: models and data should scale equally. For every doubling of model size, double the training tokens. The Chinchilla-optimal ratio is approximately 20 tokens per parameter (Epoch AI 2024 replication: ~25.6 tokens/param).\n\nConsequence: Chinchilla (70B, 1.4T tokens) outperformed Gopher (280B, 300B tokens) and GPT-3 (175B, 300B tokens) at equal compute. Most large models of 2020–2022 were severely undertrained.\n\nPost-Chinchilla industry shift: LLaMA 3 70B was trained on 15T tokens (~214 tokens/param) — deliberately overtrained relative to Chinchilla to maximize inference efficiency. A smaller model that performs well enough at lower per-token inference cost is often more economical than the compute-optimal trained model.",
        "anim": "chinchilla",
        "math": {
          "eqs": [
            {
              "l": "Optimal data-to-param ratio",
              "t": "D^*\\approx 20\\times N^*"
            },
            {
              "l": "Both scale equally",
              "t": "N^*(C)\\propto C^{1/2},\\quad D^*(C)\\propto C^{1/2}"
            }
          ]
        }
      },
      {
        "id": "timeline",
        "title": "The Model Size Timeline",
        "body": "GPT-1: 117M (2018) → BERT-Large: 340M → GPT-2: 1.5B (2019) → T5-11B → GPT-3: 175B (2020) → Megatron-Turing: 530B (2021) → PaLM: 540B (2022) → GPT-4: ~1.8T total/~280B active (rumored MoE, 2023, unconfirmed by OpenAI) → DeepSeek-V3: 671B/37B active (2024/25).\n\nKey inflection point: after GPT-3/PaLM, the frontier pivoted from dense scaling toward MoE — total parameters and active compute diverge dramatically. A 671B parameter model with 37B active compute per token is operationally much cheaper to run than a 671B dense model.\n\nOpen models (LLaMA 3 70B/405B, Qwen 2.5 72B, Mistral Large, DeepSeek-V3) have dramatically closed the capability gap with closed frontier models — a remarkable democratization enabled by the Chinchilla insight and open-source infrastructure.",
        "anim": "timeline",
        "math": {
          "eqs": [
            {
              "l": "FLOPs Estimate",
              "t": "C \\approx 6 N D"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "implications",
    "label": "12 — Implications",
    "title": "What It Means & Where It's Going",
    "color": "#55EFC4",
    "icon": "🔭",
    "subs": [
      {
        "id": "leverage",
        "title": "Highest-Leverage Research Directions",
        "body": "Based on the current landscape, these interventions have the highest expected return:\n\n1. Efficient long-context architectures — SSMs, content-dependent sparse attention (SSA/SubQ direction), and hybrid models. Directly addresses the O(n²) structural bottleneck, the biggest remaining architectural constraint.\n\n2. Tokenization reform — byte-level or character-level processing with efficient architectures would eliminate glitch tokens, multilingual inefficiency, and arithmetic/code representation pathologies.\n\n3. Training stability at scale — better optimizers (Muon, Sophia second-order methods, MuonClip) and gradient management reduce expensive restarts from loss spikes.\n\n4. Mechanistic interpretability — sparse autoencoders, circuit analysis, and probing are maturing toward engineering tools. Scalable interpretability is a prerequisite for trustworthy deployment at scale.\n\n5. Beyond next-token prediction — world-model objectives, multi-token prediction, and causal reasoning training signals may produce qualitatively more robust and compositional representations.\n\n6. Data quality over quantity — as the data wall approaches, synthetic data generation, rigorous curation pipelines, and data-efficient training curricula become the key differentiator between organizations.",
        "math": {
          "eqs": [
            {
              "l": "Scaling Axes",
              "t": "\\text{Compute}_{total} = \\text{Compute}_{train} + \\text{Compute}_{infer}"
            }
          ]
        }
      },
      {
        "id": "future",
        "title": "A Desired Future State & Its Obstacles",
        "body": "A positive future for LLM development would involve:\n• Architectural pluralism: no single family dominates — SSMs for streaming long-context, sparse MoE for knowledge-intensive tasks, dense models for low-latency inference\n• Transparent training: data provenance documented, architecture details published, evaluation methodology disclosed\n• Democratized access: models efficient enough to run on consumer hardware, removing the GPU-cluster barrier\n• Safety by design: alignment integrated into architecture and training objectives, not only as post-training patches\n• Interpretability as standard: internal representations auditable, circuits documented as engineering deliverables\n\nObstacles:\n• Compute concentration: training frontier models requires $300M–$10B capex, concentrated in 3–4 organizations\n• Incentive misalignment: safety research costs money without directly improving capability benchmarks\n• Path dependency: decades of infrastructure, tooling, and research built around the Transformer are hard to displace\n• Benchmark lock-in: research optimizes for established benchmarks rather than real-world utility\n• Regulatory lag: governance frameworks arrive years after the technology they attempt to govern"
      }
    ]
  }
]
