export { Hero } from './Hero'
export { About } from './About'
export { Projects } from './Projects'
export { Experience } from './Experience'
export { Writing } from './Writing'
export { Skills } from './Skills'
export { Contact } from './Contact'